In [3]:
import tensorflow as tf
import numpy as np

import time
import datetime as dt

tf.reset_default_graph()

# input vector of type scalar with length 2
x = tf.placeholder(tf.float32, [None, 2], name='x')
# target labels
target = tf.placeholder(tf.float32, [None, 1], name='target') 

# bias
b = tf.get_variable("b", [1]) 

# weights
w = tf.get_variable("w", [1,2]) # weight matrix W

dot_product = tf.add(tf.matmul(x, tf.transpose(w)), b)

output = tf.sigmoid(dot_product)
#output = tf.sign(dot_product)

mse = tf.reduce_mean(tf.square(target - output))

learning_rate = 0.4

# Define a training step using Gradient Decent to minimize the mean squared error
optimizer = tf.train.AdagradOptimizer(learning_rate=learning_rate).minimize(mse)
#optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate).minimize(mse)

# training data
input = np.array([[1,1],[1,2],[2,1],[1,4],[2,3],[3,3],[4,2]])
labels = np.array([[0],[0],[0],[1],[1],[1],[1]])


# ------------------------
# Visualization of flow graph
# Define summaries to be shown in TensorBoard
tf.summary.histogram("Weights", w)
tf.summary.scalar("Bias", b[0])
tf.summary.scalar("MSE", mse)

# ------------------------------
# Activate logging for TensorBoard
merged = tf.summary.merge_all()
st = dt.datetime.fromtimestamp(time.time()).strftime('%Y-%m-%d_%H-%M-%S')
train_writer = tf.summary.FileWriter('log/lr_' + st, tf.get_default_graph())
# ------------------------------


iterations = 10000
init = tf.global_variables_initializer()

with tf.Session() as sess:
    init.run()
    
    #for j in range(iterations):
    # Loop over all steps and perform training updates on W and b
    for i in range(iterations):      
        # Instead of MiniBatches we can use the whole set here
        xs = np.array(input)   # input
        ys = np.array(labels)  # blood pressure
        summary, _ = sess.run([merged, optimizer], feed_dict={ x: xs, target: ys })
        train_writer.add_summary(summary, i)

        res_mse, res_w, res_b = sess.run([mse, w, b], feed_dict={ x: xs, target: ys})
        print("\nAfter iteration: %d" % i)
        #print("MSE: %f \n" % res_mse)
        print(res_mse)
        print(res_b)
        print(w.eval())
        
        
        
        



After iteration: 0
0.404637
[ 0.45157877]
[[ 1.37721324  1.06027782]]

After iteration: 1
0.402023
[ 0.42318359]
[[ 1.34403372  1.02542686]]

After iteration: 2
0.398822
[ 0.3919625]
[[ 1.30745482  0.98698688]]

After iteration: 3
0.394827
[ 0.35734832]
[[ 1.26678443  0.94423026]]

After iteration: 4
0.389732
[ 0.31860426]
[[ 1.22112179  0.89621443]]

After iteration: 5
0.38307
[ 0.27475977]
[[ 1.16927958  0.84170455]]

After iteration: 6
0.374107
[ 0.22452322]
[[ 1.10967791  0.77907497]]

After iteration: 7
0.361666
[ 0.16617323]
[[ 1.04021597  0.70620453]]

After iteration: 8
0.343859
[ 0.09746647]
[[ 0.95817363  0.6204499 ]]

After iteration: 9
0.317867
[ 0.01572709]
[[ 0.86036003  0.51900637]]

After iteration: 10
0.2808
[-0.08129951]
[[ 0.74425244  0.40067786]]

After iteration: 11
0.235378
[-0.19219685]
[[ 0.61221075  0.27197403]]

After iteration: 12
0.200834
[-0.30393693]
[[ 0.48253185  0.16300246]]

After iteration: 13
0.189596
[-0.38926119]
[[ 0.39870203  0.13531938]]

After

After iteration: 154
0.0411839
[-3.9341557]
[[ 0.77133816  1.26032174]]

After iteration: 155
0.0409546
[-3.9465878]
[[ 0.77384013  1.26348341]]

After iteration: 156
0.0407278
[-3.95894814]
[[ 0.77632773  1.26662755]]

After iteration: 157
0.0405035
[-3.97123742]
[[ 0.77880114  1.26975429]]

After iteration: 158
0.0402816
[-3.98345661]
[[ 0.78126049  1.27286386]]

After iteration: 159
0.0400621
[-3.99560642]
[[ 0.78370595  1.27595639]]

After iteration: 160
0.0398451
[-4.00768757]
[[ 0.78613776  1.27903223]]

After iteration: 161
0.0396303
[-4.019701]
[[ 0.78855586  1.28209138]]

After iteration: 162
0.0394178
[-4.03164768]
[[ 0.79096061  1.28513408]]

After iteration: 163
0.0392076
[-4.04352808]
[[ 0.79335213  1.28816068]]

After iteration: 164
0.0389996
[-4.05534267]
[[ 0.79573053  1.29117119]]

After iteration: 165
0.0387939
[-4.06709242]
[[ 0.79809588  1.29416573]]

After iteration: 166
0.0385902
[-4.07877827]
[[ 0.80044842  1.29714465]]

After iteration: 167
0.0383887
[-4.0904002

[-5.11952019]
[[ 1.01025224  1.56477153]]

After iteration: 282
0.0239646
[-5.12667608]
[[ 1.01169705  1.56662655]]

After iteration: 283
0.0238864
[-5.13380814]
[[ 1.0131371  1.5684756]]

After iteration: 284
0.0238087
[-5.14091635]
[[ 1.0145725  1.5703187]]

After iteration: 285
0.0237314
[-5.14800119]
[[ 1.01600313  1.57215583]]

After iteration: 286
0.0236547
[-5.15506268]
[[ 1.01742911  1.57398713]]

After iteration: 287
0.0235785
[-5.16210079]
[[ 1.01885045  1.57581258]]

After iteration: 288
0.0235027
[-5.16911602]
[[ 1.02026713  1.57763219]]

After iteration: 289
0.0234274
[-5.17610836]
[[ 1.02167916  1.57944608]]

After iteration: 290
0.0233526
[-5.18307781]
[[ 1.02308667  1.58125412]]

After iteration: 291
0.0232783
[-5.19002485]
[[ 1.02448964  1.58305657]]

After iteration: 292
0.0232045
[-5.19694948]
[[ 1.0258882   1.58485341]]

After iteration: 293
0.0231311
[-5.2038517]
[[ 1.02728224  1.58664465]]

After iteration: 294
0.0230581
[-5.21073198]
[[ 1.02867186  1.58843029]]



After iteration: 426
0.0162677
[-5.9668107]
[[ 1.18166482  1.78563035]]

After iteration: 427
0.0162314
[-5.97163105]
[[ 1.18264234  1.78689337]]

After iteration: 428
0.0161952
[-5.97644043]
[[ 1.18361771  1.78815353]]

After iteration: 429
0.0161592
[-5.98123932]
[[ 1.18459094  1.78941095]]

After iteration: 430
0.0161234
[-5.98602724]
[[ 1.18556201  1.79066563]]

After iteration: 431
0.0160877
[-5.99080467]
[[ 1.18653095  1.79191756]]

After iteration: 432
0.0160522
[-5.99557114]
[[ 1.18749774  1.79316676]]

After iteration: 433
0.0160168
[-6.00032711]
[[ 1.18846238  1.79441321]]

After iteration: 434
0.0159816
[-6.00507259]
[[ 1.18942487  1.79565704]]

After iteration: 435
0.0159465
[-6.00980759]
[[ 1.19038534  1.79689813]]

After iteration: 436
0.0159116
[-6.01453209]
[[ 1.19134367  1.79813659]]

After iteration: 437
0.0158769
[-6.0192461]
[[ 1.19229996  1.79937232]]

After iteration: 438
0.0158422
[-6.0239501]
[[ 1.19325411  1.80060542]]

After iteration: 439
0.0158078
[-6.028643


After iteration: 568
0.0123372
[-6.5612483]
[[ 1.30246961  1.94184184]]

After iteration: 569
0.0123161
[-6.56489944]
[[ 1.30321348  1.9428041 ]]

After iteration: 570
0.0122952
[-6.56854439]
[[ 1.30395603  1.94376469]]

After iteration: 571
0.0122743
[-6.57218313]
[[ 1.30469739  1.94472361]]

After iteration: 572
0.0122535
[-6.57581568]
[[ 1.30543756  1.94568098]]

After iteration: 573
0.0122328
[-6.57944202]
[[ 1.30617642  1.9466368 ]]

After iteration: 574
0.0122121
[-6.58306265]
[[ 1.30691409  1.94759095]]

After iteration: 575
0.0121915
[-6.58667707]
[[ 1.30765057  1.94854355]]

After iteration: 576
0.012171
[-6.5902853]
[[ 1.30838573  1.9494946 ]]

After iteration: 577
0.0121506
[-6.59388733]
[[ 1.3091197  1.9504441]]

After iteration: 578
0.0121302
[-6.59748316]
[[ 1.30985248  1.95139194]]

After iteration: 579
0.0121099
[-6.60107327]
[[ 1.31058407  1.95233822]]

After iteration: 580
0.0120896
[-6.60465717]
[[ 1.31131446  1.95328295]]

After iteration: 581
0.0120694
[-6.6082348

[-7.05494738]
[[ 1.40327752  2.07219195]]

After iteration: 721
0.00977852
[-7.05784464]
[[ 1.40387058  2.07295823]]

After iteration: 722
0.00976525
[-7.06073809]
[[ 1.40446293  2.07372355]]

After iteration: 723
0.00975202
[-7.06362772]
[[ 1.40505445  2.07448792]]

After iteration: 724
0.00973882
[-7.06651354]
[[ 1.40564525  2.0752511 ]]

After iteration: 725
0.00972566
[-7.06939554]
[[ 1.40623522  2.07601333]]

After iteration: 726
0.00971254
[-7.07227325]
[[ 1.40682447  2.0767746 ]]

After iteration: 727
0.00969944
[-7.07514715]
[[ 1.40741289  2.07753491]]

After iteration: 728
0.00968639
[-7.07801723]
[[ 1.40800047  2.07829404]]

After iteration: 729
0.00967337
[-7.0808835]
[[ 1.40858734  2.07905221]]

After iteration: 730
0.00966038
[-7.08374596]
[[ 1.40917349  2.07980943]]

After iteration: 731
0.00964743
[-7.0866046]
[[ 1.40975881  2.08056569]]

After iteration: 732
0.00963451
[-7.08945942]
[[ 1.41034341  2.081321  ]]

After iteration: 733
0.00962163
[-7.09231043]
[[ 1.41092718

After iteration: 861
0.00821338
[-7.42891693]
[[ 1.47998917  2.1712153 ]]

After iteration: 862
0.00820398
[-7.43134785]
[[ 1.4804889   2.17185974]]

After iteration: 863
0.00819461
[-7.4337759]
[[ 1.48098803  2.17250323]]

After iteration: 864
0.00818526
[-7.4362011]
[[ 1.48148668  2.17314601]]

After iteration: 865
0.00817592
[-7.43862391]
[[ 1.48198473  2.17378807]]

After iteration: 866
0.00816661
[-7.44104385]
[[ 1.48248231  2.17442942]]

After iteration: 867
0.00815732
[-7.44346094]
[[ 1.4829793   2.17507005]]

After iteration: 868
0.00814805
[-7.44587517]
[[ 1.4834758   2.17570996]]

After iteration: 869
0.0081388
[-7.44828653]
[[ 1.48397171  2.17634916]]

After iteration: 870
0.00812957
[-7.45069551]
[[ 1.48446703  2.17698765]]

After iteration: 871
0.00812037
[-7.45310163]
[[ 1.48496187  2.17762566]]

After iteration: 872
0.00811118
[-7.45550489]
[[ 1.48545611  2.17826271]]

After iteration: 873
0.00810201
[-7.45790577]
[[ 1.48594987  2.17889905]]

After iteration: 874
0.00809

[[ 1.54113686  2.24996257]]

After iteration: 993
0.00713338
[-7.72792149]
[[ 1.54157317  2.25052357]]

After iteration: 994
0.00712628
[-7.7300334]
[[ 1.542009    2.25108409]]

After iteration: 995
0.00711919
[-7.7321434]
[[ 1.54244447  2.25164413]]

After iteration: 996
0.0071121
[-7.73425102]
[[ 1.54287946  2.2522037 ]]

After iteration: 997
0.00710504
[-7.73635674]
[[ 1.54331398  2.25276256]]

After iteration: 998
0.00709798
[-7.73846006]
[[ 1.54374814  2.25332093]]

After iteration: 999
0.00709095
[-7.74056149]
[[ 1.54418182  2.25387859]]

After iteration: 1000
0.00708392
[-7.742661]
[[ 1.54461515  2.25443578]]

After iteration: 1001
0.00707691
[-7.74475813]
[[ 1.545048    2.25499249]]

After iteration: 1002
0.00706991
[-7.74685335]
[[ 1.54548049  2.25554872]]

After iteration: 1003
0.00706293
[-7.74894667]
[[ 1.54591262  2.25610423]]

After iteration: 1004
0.00705596
[-7.7510376]
[[ 1.54634428  2.25665927]]

After iteration: 1005
0.007049
[-7.75312662]
[[ 1.54677558  2.25721383]]

After iteration: 1147
0.00618226
[-8.03065395]
[[ 1.60417652  2.33091259]]

After iteration: 1148
0.00617691
[-8.03248501]
[[ 1.60455596  2.33139896]]

After iteration: 1149
0.00617156
[-8.03431416]
[[ 1.60493517  2.3318851 ]]

After iteration: 1150
0.00616622
[-8.03614235]
[[ 1.60531402  2.33237076]]

After iteration: 1151
0.0061609
[-8.03796864]
[[ 1.60569251  2.33285594]]

After iteration: 1152
0.00615557
[-8.03979301]
[[ 1.60607076  2.33334064]]

After iteration: 1153
0.00615027
[-8.04161644]
[[ 1.60644865  2.33382487]]

After iteration: 1154
0.00614497
[-8.04343796]
[[ 1.60682619  2.33430886]]

After iteration: 1155
0.00613967
[-8.04525852]
[[ 1.60720348  2.33479238]]

After iteration: 1156
0.00613439
[-8.04707718]
[[ 1.60758042  2.33527541]]

After iteration: 1157
0.00612912
[-8.04889393]
[[ 1.60795712  2.33575821]]

After iteration: 1158
0.00612385
[-8.05070972]
[[ 1.60833347  2.33624053]]

After iteration: 1159
0.0061186
[-8.05252361]
[[ 1.60870945  2.33672237]]

After iteratio

After iteration: 1260
0.00563015
[-8.22815895]
[[ 1.64516604  2.38339496]]

After iteration: 1261
0.00562569
[-8.22982693]
[[ 1.6455127   2.38383842]]

After iteration: 1262
0.00562125
[-8.23149395]
[[ 1.64585912  2.3842814 ]]

After iteration: 1263
0.00561681
[-8.23315907]
[[ 1.64620531  2.38472414]]

After iteration: 1264
0.00561239
[-8.23482323]
[[ 1.64655125  2.38516641]]

After iteration: 1265
0.00560796
[-8.23648643]
[[ 1.64689696  2.38560843]]

After iteration: 1266
0.00560355
[-8.23814774]
[[ 1.64724231  2.38604999]]

After iteration: 1267
0.00559914
[-8.23980808]
[[ 1.64758742  2.3864913 ]]

After iteration: 1268
0.00559474
[-8.24146748]
[[ 1.64793229  2.38693213]]

After iteration: 1269
0.00559034
[-8.24312496]
[[ 1.64827693  2.38737273]]

After iteration: 1270
0.00558595
[-8.24478149]
[[ 1.64862132  2.38781309]]

After iteration: 1271
0.00558157
[-8.24643707]
[[ 1.64896536  2.38825297]]

After iteration: 1272
0.0055772
[-8.24809074]
[[ 1.64930916  2.38869262]]

After iterati

After iteration: 1409
0.00503592
[-8.46325302]
[[ 1.6941179   2.44589067]]

After iteration: 1410
0.00503235
[-8.46474552]
[[ 1.69442928  2.44628763]]

After iteration: 1411
0.00502879
[-8.46623707]
[[ 1.69474041  2.44668412]]

After iteration: 1412
0.00502523
[-8.46772766]
[[ 1.69505143  2.44708037]]

After iteration: 1413
0.00502168
[-8.4692173]
[[ 1.69536221  2.44747639]]

After iteration: 1414
0.00501813
[-8.47070599]
[[ 1.69567275  2.44787216]]

After iteration: 1415
0.00501459
[-8.47219372]
[[ 1.69598305  2.4482677 ]]

After iteration: 1416
0.00501105
[-8.4736805]
[[ 1.69629323  2.448663  ]]

After iteration: 1417
0.00500752
[-8.47516632]
[[ 1.69660318  2.44905806]]

After iteration: 1418
0.00500399
[-8.47665024]
[[ 1.69691288  2.44945264]]

After iteration: 1419
0.00500046
[-8.4781332]
[[ 1.69722235  2.44984698]]

After iteration: 1420
0.00499695
[-8.47961521]
[[ 1.6975317   2.45024109]]

After iteration: 1421
0.00499343
[-8.48109627]
[[ 1.69784081  2.45063496]]

After iteration

After iteration: 1558
0.00455425
[-8.67481041]
[[ 1.73832703  2.50214291]]

After iteration: 1559
0.00455133
[-8.67616081]
[[ 1.73860979  2.50250196]]

After iteration: 1560
0.00454841
[-8.67751026]
[[ 1.73889232  2.50286078]]

After iteration: 1561
0.00454549
[-8.67885876]
[[ 1.73917472  2.50321937]]

After iteration: 1562
0.00454258
[-8.6802063]
[[ 1.73945689  2.50357771]]

After iteration: 1563
0.00453967
[-8.68155384]
[[ 1.73973894  2.50393581]]

After iteration: 1564
0.00453676
[-8.68290043]
[[ 1.74002075  2.50429368]]

After iteration: 1565
0.00453386
[-8.68424606]
[[ 1.74030244  2.50465155]]

After iteration: 1566
0.00453096
[-8.68559074]
[[ 1.74058402  2.50500917]]

After iteration: 1567
0.00452807
[-8.68693447]
[[ 1.74086535  2.50536656]]

After iteration: 1568
0.00452517
[-8.68827724]
[[ 1.74114656  2.50572371]]

After iteration: 1569
0.00452229
[-8.68961906]
[[ 1.74142754  2.50608063]]

After iteration: 1570
0.0045194
[-8.69095993]
[[ 1.7417084  2.5064373]]

After iteration:

After iteration: 1700
0.0041732
[-8.85842609]
[[ 1.77682555  2.55096745]]

After iteration: 1701
0.00417074
[-8.85966396]
[[ 1.77708554  2.55129671]]

After iteration: 1702
0.00416828
[-8.86090088]
[[ 1.77734542  2.55162573]]

After iteration: 1703
0.00416582
[-8.86213779]
[[ 1.77760506  2.55195451]]

After iteration: 1704
0.00416338
[-8.86337376]
[[ 1.77786458  2.55228305]]

After iteration: 1705
0.00416093
[-8.86460876]
[[ 1.77812397  2.55261159]]

After iteration: 1706
0.00415848
[-8.86584282]
[[ 1.77838326  2.55293989]]

After iteration: 1707
0.00415604
[-8.86707687]
[[ 1.7786423   2.55326796]]

After iteration: 1708
0.0041536
[-8.86830997]
[[ 1.77890122  2.55359578]]

After iteration: 1709
0.00415116
[-8.86954212]
[[ 1.77916002  2.55392337]]

After iteration: 1710
0.00414873
[-8.87077332]
[[ 1.77941871  2.55425072]]

After iteration: 1711
0.0041463
[-8.87200451]
[[ 1.77967727  2.55457807]]

After iteration: 1712
0.00414387
[-8.87323475]
[[ 1.7799356   2.55490518]]

After iteration

[[ 1.8113842   2.59465957]]

After iteration: 1839
0.00385683
[-9.02389622]
[[ 1.81162536  2.59496403]]

After iteration: 1840
0.00385473
[-9.02504063]
[[ 1.8118664   2.59526825]]

After iteration: 1841
0.00385262
[-9.02618504]
[[ 1.81210732  2.59557247]]

After iteration: 1842
0.00385052
[-9.02732849]
[[ 1.81234813  2.59587646]]

After iteration: 1843
0.00384843
[-9.02847099]
[[ 1.81258881  2.5961802 ]]

After iteration: 1844
0.00384633
[-9.02961349]
[[ 1.81282938  2.59648395]]

After iteration: 1845
0.00384424
[-9.03075504]
[[ 1.81306982  2.59678745]]

After iteration: 1846
0.00384215
[-9.03189564]
[[ 1.81331015  2.59709072]]

After iteration: 1847
0.00384006
[-9.03303623]
[[ 1.81355035  2.59739399]]

After iteration: 1848
0.00383798
[-9.03417587]
[[ 1.81379044  2.59769702]]

After iteration: 1849
0.00383589
[-9.03531456]
[[ 1.81403041  2.59799981]]

After iteration: 1850
0.00383381
[-9.03645325]
[[ 1.81427026  2.59830236]]

After iteration: 1851
0.00383173
[-9.03759098]
[[ 1.8145099

After iteration: 1972
0.00359566
[-9.17091751]
[[ 1.84263325  2.63404918]]

After iteration: 1973
0.00359382
[-9.17198467]
[[ 1.84285867  2.6343329 ]]

After iteration: 1974
0.003592
[-9.17305183]
[[ 1.84308398  2.63461637]]

After iteration: 1975
0.00359017
[-9.17411804]
[[ 1.84330916  2.63489985]]

After iteration: 1976
0.00358834
[-9.17518425]
[[ 1.84353423  2.6351831 ]]

After iteration: 1977
0.00358652
[-9.1762495]
[[ 1.8437593   2.63546634]]

After iteration: 1978
0.0035847
[-9.1773138]
[[ 1.84398425  2.63574934]]

After iteration: 1979
0.00358288
[-9.17837811]
[[ 1.84420907  2.6360321 ]]

After iteration: 1980
0.00358106
[-9.17944145]
[[ 1.84443378  2.63631487]]

After iteration: 1981
0.00357924
[-9.1805048]
[[ 1.84465837  2.63659739]]

After iteration: 1982
0.00357743
[-9.18156719]
[[ 1.84488285  2.63687992]]

After iteration: 1983
0.00357562
[-9.18262959]
[[ 1.8451072   2.63716221]]

After iteration: 1984
0.0035738
[-9.18369102]
[[ 1.84533143  2.6374445 ]]

After iteration: 19

After iteration: 2095
0.0033835
[-9.29831505]
[[ 1.86957061  2.66790986]]

After iteration: 2096
0.00338188
[-9.29932022]
[[ 1.86978328  2.66817689]]

After iteration: 2097
0.00338026
[-9.30032444]
[[ 1.86999595  2.66844392]]

After iteration: 2098
0.00337864
[-9.30132866]
[[ 1.8702085   2.66871071]]

After iteration: 2099
0.00337702
[-9.30233192]
[[ 1.87042093  2.6689775 ]]

After iteration: 2100
0.0033754
[-9.30333519]
[[ 1.87063324  2.66924405]]

After iteration: 2101
0.00337379
[-9.3043375]
[[ 1.87084544  2.66951036]]

After iteration: 2102
0.00337217
[-9.30533981]
[[ 1.87105763  2.66977668]]

After iteration: 2103
0.00337056
[-9.30634117]
[[ 1.8712697   2.67004275]]

After iteration: 2104
0.00336895
[-9.30734253]
[[ 1.87148166  2.67030883]]

After iteration: 2105
0.00336734
[-9.30834293]
[[ 1.87169349  2.67057467]]

After iteration: 2106
0.00336573
[-9.30934334]
[[ 1.87190521  2.6708405 ]]

After iteration: 2107
0.00336413
[-9.31034279]
[[ 1.87211692  2.6711061 ]]

After iteration

After iteration: 2260
0.00313506
[-9.45793533]
[[ 1.90341353  2.71032453]]

After iteration: 2261
0.00313367
[-9.45886707]
[[ 1.9036113  2.710572 ]]

After iteration: 2262
0.00313227
[-9.45979786]
[[ 1.90380895  2.71081924]]

After iteration: 2263
0.00313088
[-9.46072865]
[[ 1.9040066   2.71106648]]

After iteration: 2264
0.00312949
[-9.46165848]
[[ 1.90420413  2.71131349]]

After iteration: 2265
0.00312809
[-9.46258831]
[[ 1.90440154  2.71156049]]

After iteration: 2266
0.00312671
[-9.46351719]
[[ 1.90459895  2.71180749]]

After iteration: 2267
0.00312532
[-9.46444607]
[[ 1.90479624  2.71205425]]

After iteration: 2268
0.00312393
[-9.46537495]
[[ 1.90499341  2.71230102]]

After iteration: 2269
0.00312255
[-9.46630287]
[[ 1.90519047  2.71254754]]

After iteration: 2270
0.00312116
[-9.4672308]
[[ 1.90538752  2.71279407]]

After iteration: 2271
0.00311978
[-9.46815777]
[[ 1.90558445  2.71304035]]

After iteration: 2272
0.0031184
[-9.46908474]
[[ 1.90578127  2.71328664]]

After iteration:

[-9.59322166]
[[ 1.93217957  2.74625993]]

After iteration: 2411
0.00293743
[-9.59409523]
[[ 1.93236554  2.74649191]]

After iteration: 2412
0.00293621
[-9.59496784]
[[ 1.93255138  2.74672365]]

After iteration: 2413
0.00293498
[-9.59584045]
[[ 1.93273723  2.74695539]]

After iteration: 2414
0.00293376
[-9.59671307]
[[ 1.93292296  2.74718714]]

After iteration: 2415
0.00293253
[-9.59758472]
[[ 1.93310857  2.74741864]]

After iteration: 2416
0.00293131
[-9.59845638]
[[ 1.93329418  2.74765015]]

After iteration: 2417
0.00293009
[-9.59932709]
[[ 1.93347967  2.74788141]]

After iteration: 2418
0.00292887
[-9.60019779]
[[ 1.93366504  2.74811268]]

After iteration: 2419
0.00292765
[-9.6010685]
[[ 1.93385041  2.74834394]]

After iteration: 2420
0.00292643
[-9.60193825]
[[ 1.93403566  2.74857497]]

After iteration: 2421
0.00292521
[-9.602808]
[[ 1.93422091  2.748806  ]]

After iteration: 2422
0.002924
[-9.60367775]
[[ 1.93440604  2.74903679]]

After iteration: 2423
0.00292278
[-9.60454655]
[[ 

After iteration: 2561
0.00276415
[-9.72114182]
[[ 1.95945084  2.78022575]]

After iteration: 2562
0.00276306
[-9.72196388]
[[ 1.9596262   2.78044391]]

After iteration: 2563
0.00276198
[-9.722785]
[[ 1.95980155  2.78066206]]

After iteration: 2564
0.00276089
[-9.72360611]
[[ 1.95997679  2.78087997]]

After iteration: 2565
0.00275981
[-9.72442722]
[[ 1.96015203  2.78109789]]

After iteration: 2566
0.00275872
[-9.72524738]
[[ 1.96032715  2.7813158 ]]

After iteration: 2567
0.00275764
[-9.72606754]
[[ 1.96050227  2.78153348]]

After iteration: 2568
0.00275656
[-9.7268877]
[[ 1.96067727  2.78175116]]

After iteration: 2569
0.00275548
[-9.72770691]
[[ 1.96085227  2.78196859]]

After iteration: 2570
0.0027544
[-9.72852612]
[[ 1.96102715  2.78218603]]

After iteration: 2571
0.00275331
[-9.72934532]
[[ 1.96120203  2.78240347]]

After iteration: 2572
0.00275224
[-9.73016357]
[[ 1.96137679  2.78262067]]

After iteration: 2573
0.00275116
[-9.73098183]
[[ 1.96155143  2.78283787]]

After iteration:

After iteration: 2717
0.00260421
[-9.84559345]
[[ 1.98605096  2.81325698]]

After iteration: 2718
0.00260324
[-9.84636784]
[[ 1.98621666  2.8134625 ]]

After iteration: 2719
0.00260228
[-9.84714222]
[[ 1.98638237  2.81366801]]

After iteration: 2720
0.00260131
[-9.84791565]
[[ 1.98654795  2.81387329]]

After iteration: 2721
0.00260035
[-9.84868908]
[[ 1.98671353  2.81407857]]

After iteration: 2722
0.00259938
[-9.84946251]
[[ 1.98687899  2.81428385]]

After iteration: 2723
0.00259842
[-9.85023594]
[[ 1.98704445  2.81448889]]

After iteration: 2724
0.00259746
[-9.85100842]
[[ 1.9872098   2.81469393]]

After iteration: 2725
0.0025965
[-9.85178089]
[[ 1.98737514  2.81489897]]

After iteration: 2726
0.00259554
[-9.85255337]
[[ 1.98754036  2.81510377]]

After iteration: 2727
0.00259458
[-9.85332489]
[[ 1.98770559  2.81530857]]

After iteration: 2728
0.00259362
[-9.85409641]
[[ 1.98787069  2.81551337]]

After iteration: 2729
0.00259266
[-9.85486794]
[[ 1.9880358   2.81571794]]

After iterati

[-9.95646954]
[[ 2.00980663  2.84267282]]

After iteration: 2865
0.00246857
[-9.95720387]
[[ 2.00996423  2.84286761]]

After iteration: 2866
0.0024677
[-9.95793819]
[[ 2.01012182  2.8430624 ]]

After iteration: 2867
0.00246683
[-9.95867252]
[[ 2.01027918  2.84325719]]

After iteration: 2868
0.00246596
[-9.9594059]
[[ 2.01043653  2.84345174]]

After iteration: 2869
0.00246509
[-9.96013927]
[[ 2.01059389  2.84364629]]

After iteration: 2870
0.00246423
[-9.96087265]
[[ 2.01075125  2.84384084]]

After iteration: 2871
0.00246336
[-9.96160603]
[[ 2.01090837  2.84403515]]

After iteration: 2872
0.0024625
[-9.96233845]
[[ 2.01106548  2.84422946]]

After iteration: 2873
0.00246163
[-9.96307087]
[[ 2.0112226   2.84442377]]

After iteration: 2874
0.00246077
[-9.96380329]
[[ 2.01137972  2.84461808]]

After iteration: 2875
0.0024599
[-9.96453571]
[[ 2.01153684  2.84481215]]

After iteration: 2876
0.00245904
[-9.96526718]
[[ 2.01169372  2.84500623]]

After iteration: 2877
0.00245818
[-9.96599865]
[[

[[ 2.03347039  2.87189341]]

After iteration: 3019
0.00234155
[-10.06735611]
[[ 2.03362036  2.87207818]]

After iteration: 3020
0.00234077
[-10.06805325]
[[ 2.03377008  2.87226295]]

After iteration: 3021
0.00233999
[-10.06874943]
[[ 2.03391981  2.87244749]]

After iteration: 3022
0.0023392
[-10.06944561]
[[ 2.03406954  2.87263203]]

After iteration: 3023
0.00233842
[-10.07014179]
[[ 2.03421926  2.87281656]]

After iteration: 3024
0.00233764
[-10.07083797]
[[ 2.03436899  2.8730011 ]]

After iteration: 3025
0.00233686
[-10.0715332]
[[ 2.03451848  2.8731854 ]]

After iteration: 3026
0.00233608
[-10.07222843]
[[ 2.03466797  2.87336969]]

After iteration: 3027
0.0023353
[-10.07292366]
[[ 2.03481746  2.87355399]]

After iteration: 3028
0.00233453
[-10.07361889]
[[ 2.03496695  2.87373829]]

After iteration: 3029
0.00233375
[-10.07431316]
[[ 2.03511643  2.87392235]]

After iteration: 3030
0.00233297
[-10.07500744]
[[ 2.03526568  2.87410641]]

After iteration: 3031
0.0023322
[-10.07570171]
[[ 

[[ 2.05628991  2.89999247]]

After iteration: 3175
0.00222545
[-10.17333317]
[[ 2.05643272  2.90016794]]

After iteration: 3176
0.00222474
[-10.17399597]
[[ 2.05657554  2.90034342]]

After iteration: 3177
0.00222404
[-10.17465782]
[[ 2.05671835  2.90051889]]

After iteration: 3178
0.00222333
[-10.17531967]
[[ 2.05686092  2.90069437]]

After iteration: 3179
0.00222263
[-10.17598152]
[[ 2.0570035   2.90086961]]

After iteration: 3180
0.00222192
[-10.17664337]
[[ 2.05714607  2.90104485]]

After iteration: 3181
0.00222122
[-10.17730427]
[[ 2.05728865  2.90122008]]

After iteration: 3182
0.00222051
[-10.17796516]
[[ 2.05743122  2.90139532]]

After iteration: 3183
0.00221981
[-10.17862606]
[[ 2.05757356  2.90157056]]

After iteration: 3184
0.0022191
[-10.17928696]
[[ 2.05771589  2.90174556]]

After iteration: 3185
0.0022184
[-10.17994785]
[[ 2.05785823  2.90192056]]

After iteration: 3186
0.0022177
[-10.1806078]
[[ 2.05800056  2.90209556]]

After iteration: 3187
0.00221699
[-10.18126774]
[[ 

[-10.26725006]
[[ 2.07669234  2.92505026]]

After iteration: 3321
0.00212669
[-10.2678833]
[[ 2.0768292   2.92521811]]

After iteration: 3322
0.00212604
[-10.26851654]
[[ 2.07696581  2.92538571]]

After iteration: 3323
0.0021254
[-10.26914978]
[[ 2.07710242  2.92555332]]

After iteration: 3324
0.00212475
[-10.26978207]
[[ 2.07723904  2.92572093]]

After iteration: 3325
0.0021241
[-10.27041435]
[[ 2.07737565  2.92588854]]

After iteration: 3326
0.00212346
[-10.27104664]
[[ 2.07751226  2.92605591]]

After iteration: 3327
0.00212282
[-10.27167892]
[[ 2.07764888  2.92622328]]

After iteration: 3328
0.00212217
[-10.27231121]
[[ 2.07778525  2.92639065]]

After iteration: 3329
0.00212153
[-10.27294254]
[[ 2.07792163  2.92655802]]

After iteration: 3330
0.00212088
[-10.27357388]
[[ 2.078058    2.92672539]]

After iteration: 3331
0.00212024
[-10.27420521]
[[ 2.07819438  2.92689252]]

After iteration: 3332
0.0021196
[-10.27483654]
[[ 2.07833076  2.92705965]]

After iteration: 3333
0.00211896
[-1


After iteration: 3461
0.00203982
[-10.35470486]
[[ 2.09559536  2.94821   ]]

After iteration: 3462
0.00203922
[-10.35531235]
[[ 2.09572673  2.9483707 ]]

After iteration: 3463
0.00203863
[-10.35591984]
[[ 2.0958581   2.94853139]]

After iteration: 3464
0.00203804
[-10.35652733]
[[ 2.09598947  2.94869208]]

After iteration: 3465
0.00203744
[-10.35713387]
[[ 2.09612083  2.94885278]]

After iteration: 3466
0.00203685
[-10.3577404]
[[ 2.0962522   2.94901347]]

After iteration: 3467
0.00203626
[-10.35834694]
[[ 2.09638333  2.94917417]]

After iteration: 3468
0.00203566
[-10.35895348]
[[ 2.09651446  2.94933462]]

After iteration: 3469
0.00203507
[-10.35956001]
[[ 2.09664559  2.94949508]]

After iteration: 3470
0.00203448
[-10.3601656]
[[ 2.09677672  2.94965553]]

After iteration: 3471
0.00203388
[-10.36077118]
[[ 2.09690785  2.94981599]]

After iteration: 3472
0.00203329
[-10.36137676]
[[ 2.09703898  2.94997621]]

After iteration: 3473
0.0020327
[-10.36198235]
[[ 2.09717011  2.95013642]]

A

After iteration: 3632
0.00194282
[-10.45608616]
[[ 2.1175549   2.97504449]]

After iteration: 3633
0.00194228
[-10.45666504]
[[ 2.11768031  2.97519755]]

After iteration: 3634
0.00194174
[-10.45724392]
[[ 2.11780572  2.97535062]]

After iteration: 3635
0.0019412
[-10.45782185]
[[ 2.11793113  2.97550368]]

After iteration: 3636
0.00194066
[-10.45839977]
[[ 2.11805654  2.97565675]]

After iteration: 3637
0.00194012
[-10.4589777]
[[ 2.11818194  2.97580957]]

After iteration: 3638
0.00193958
[-10.45955563]
[[ 2.11830735  2.9759624 ]]

After iteration: 3639
0.00193904
[-10.46013355]
[[ 2.11843252  2.97611523]]

After iteration: 3640
0.0019385
[-10.46071148]
[[ 2.11855769  2.97626805]]

After iteration: 3641
0.00193797
[-10.46128845]
[[ 2.11868286  2.97642088]]

After iteration: 3642
0.00193743
[-10.46186543]
[[ 2.11880803  2.97657371]]

After iteration: 3643
0.00193689
[-10.4624424]
[[ 2.1189332   2.97672629]]

After iteration: 3644
0.00193635
[-10.46301937]
[[ 2.11905837  2.97687888]]

Aft

0.0018841
[-10.51992035]
[[ 2.13140678  2.99193287]]

After iteration: 3745
0.00188359
[-10.52048206]
[[ 2.13152862  2.9920814 ]]

After iteration: 3746
0.00188308
[-10.52104282]
[[ 2.13165045  2.99222994]]

After iteration: 3747
0.00188257
[-10.52160358]
[[ 2.13177228  2.99237823]]

After iteration: 3748
0.00188207
[-10.52216434]
[[ 2.13189411  2.99252653]]

After iteration: 3749
0.00188156
[-10.52272511]
[[ 2.13201594  2.99267483]]

After iteration: 3750
0.00188105
[-10.52328587]
[[ 2.13213778  2.99282312]]

After iteration: 3751
0.00188054
[-10.52384663]
[[ 2.13225937  2.99297142]]

After iteration: 3752
0.00188003
[-10.52440643]
[[ 2.13238096  2.99311972]]

After iteration: 3753
0.00187953
[-10.52496624]
[[ 2.13250256  2.99326777]]

After iteration: 3754
0.00187902
[-10.52552605]
[[ 2.13262415  2.99341583]]

After iteration: 3755
0.00187852
[-10.52608585]
[[ 2.13274574  2.99356389]]

After iteration: 3756
0.00187801
[-10.52664566]
[[ 2.13286734  2.99371195]]

After iteration: 3757


0.00181831
[-10.59381962]
[[ 2.14746761  3.01147723]]

After iteration: 3879
0.00181783
[-10.59436131]
[[ 2.14758539  3.01162052]]

After iteration: 3880
0.00181736
[-10.59490299]
[[ 2.14770317  3.01176381]]

After iteration: 3881
0.00181689
[-10.59544468]
[[ 2.14782095  3.0119071 ]]

After iteration: 3882
0.00181641
[-10.59598637]
[[ 2.14793873  3.01205015]]

After iteration: 3883
0.00181594
[-10.59652805]
[[ 2.14805651  3.0121932 ]]

After iteration: 3884
0.00181547
[-10.59706879]
[[ 2.14817429  3.01233625]]

After iteration: 3885
0.00181499
[-10.59760952]
[[ 2.14829206  3.01247931]]

After iteration: 3886
0.00181452
[-10.59815025]
[[ 2.14840961  3.01262236]]

After iteration: 3887
0.00181405
[-10.59869099]
[[ 2.14852715  3.01276541]]

After iteration: 3888
0.00181358
[-10.59923172]
[[ 2.14864469  3.01290822]]

After iteration: 3889
0.00181311
[-10.59977245]
[[ 2.14876223  3.01305103]]

After iteration: 3890
0.00181264
[-10.60031223]
[[ 2.14887977  3.01319385]]

After iteration: 3891

[-10.66938019]
[[ 2.1639173   3.03145242]]

After iteration: 4021
0.00175295
[-10.6699028]
[[ 2.16403127  3.03159046]]

After iteration: 4022
0.00175251
[-10.67042542]
[[ 2.16414499  3.03172851]]

After iteration: 4023
0.00175206
[-10.67094803]
[[ 2.16425872  3.03186655]]

After iteration: 4024
0.00175162
[-10.67147064]
[[ 2.16437244  3.03200459]]

After iteration: 4025
0.00175119
[-10.6719923]
[[ 2.16448617  3.03214264]]

After iteration: 4026
0.00175074
[-10.67251396]
[[ 2.1645999   3.03228068]]

After iteration: 4027
0.00175031
[-10.67303562]
[[ 2.16471362  3.03241849]]

After iteration: 4028
0.00174987
[-10.67355728]
[[ 2.16482735  3.0325563 ]]

After iteration: 4029
0.00174943
[-10.67407894]
[[ 2.16494107  3.0326941 ]]

After iteration: 4030
0.00174899
[-10.6746006]
[[ 2.1650548   3.03283191]]

After iteration: 4031
0.00174855
[-10.67512226]
[[ 2.16516829  3.03296971]]

After iteration: 4032
0.00174811
[-10.67564297]
[[ 2.16528177  3.03310752]]

After iteration: 4033
0.00174767
[-

[[ 2.17605948  3.04616928]]

After iteration: 4129
0.00170659
[-10.72558212]
[[ 2.17617059  3.04630375]]

After iteration: 4130
0.00170618
[-10.72609043]
[[ 2.17628169  3.04643822]]

After iteration: 4131
0.00170576
[-10.72659874]
[[ 2.17639256  3.04657269]]

After iteration: 4132
0.00170534
[-10.72710705]
[[ 2.17650342  3.04670691]]

After iteration: 4133
0.00170492
[-10.72761536]
[[ 2.17661428  3.04684114]]

After iteration: 4134
0.0017045
[-10.72812366]
[[ 2.17672515  3.04697537]]

After iteration: 4135
0.00170409
[-10.72863197]
[[ 2.17683601  3.0471096 ]]

After iteration: 4136
0.00170367
[-10.72914028]
[[ 2.17694688  3.04724383]]

After iteration: 4137
0.00170326
[-10.72964764]
[[ 2.17705774  3.04737806]]

After iteration: 4138
0.00170284
[-10.73015499]
[[ 2.17716861  3.04751229]]

After iteration: 4139
0.00170242
[-10.73066235]
[[ 2.17727947  3.04764628]]

After iteration: 4140
0.00170201
[-10.7311697]
[[ 2.1773901   3.04778028]]

After iteration: 4141
0.00170159
[-10.73167706]
[

[-10.79905701]
[[ 2.19221473  3.06571174]]

After iteration: 4277
0.00164689
[-10.79954815]
[[ 2.19232202  3.06584144]]

After iteration: 4278
0.0016465
[-10.80003929]
[[ 2.1924293   3.06597114]]

After iteration: 4279
0.00164611
[-10.80053043]
[[ 2.19253659  3.06610084]]

After iteration: 4280
0.00164572
[-10.80102158]
[[ 2.19264388  3.06623054]]

After iteration: 4281
0.00164533
[-10.80151176]
[[ 2.19275117  3.06636   ]]

After iteration: 4282
0.00164494
[-10.80200195]
[[ 2.19285846  3.06648946]]

After iteration: 4283
0.00164455
[-10.80249214]
[[ 2.19296575  3.06661892]]

After iteration: 4284
0.00164416
[-10.80298233]
[[ 2.1930728   3.06674838]]

After iteration: 4285
0.00164378
[-10.80347252]
[[ 2.19317985  3.06687784]]

After iteration: 4286
0.00164339
[-10.80396271]
[[ 2.1932869  3.0670073]]

After iteration: 4287
0.001643
[-10.8044529]
[[ 2.19339395  3.06713676]]

After iteration: 4288
0.00164261
[-10.80494308]
[[ 2.193501    3.06726623]]

After iteration: 4289
0.00164222
[-10.


After iteration: 4399
0.0016007
[-10.85861206]
[[ 2.20523858  3.0814364 ]]

After iteration: 4400
0.00160033
[-10.8590889]
[[ 2.20534301  3.08156228]]

After iteration: 4401
0.00159996
[-10.85956573]
[[ 2.20544744  3.08168817]]

After iteration: 4402
0.00159959
[-10.86004257]
[[ 2.20555186  3.08181405]]

After iteration: 4403
0.00159923
[-10.86051941]
[[ 2.20565629  3.08193994]]

After iteration: 4404
0.00159886
[-10.86099625]
[[ 2.20576072  3.08206582]]

After iteration: 4405
0.00159849
[-10.86147308]
[[ 2.20586514  3.08219171]]

After iteration: 4406
0.00159812
[-10.86194992]
[[ 2.20596957  3.08231759]]

After iteration: 4407
0.00159776
[-10.86242676]
[[ 2.20607376  3.08244348]]

After iteration: 4408
0.00159739
[-10.86290359]
[[ 2.20617795  3.08256936]]

After iteration: 4409
0.00159702
[-10.86337948]
[[ 2.20628214  3.08269501]]

After iteration: 4410
0.00159666
[-10.86385536]
[[ 2.20638633  3.08282065]]

After iteration: 4411
0.00159629
[-10.86433125]
[[ 2.20649052  3.0829463 ]]



[[ 2.21679807  3.09536886]]

After iteration: 4512
0.00156015
[-10.91186428]
[[ 2.21690011  3.09549165]]

After iteration: 4513
0.0015598
[-10.91232967]
[[ 2.21700215  3.09561443]]

After iteration: 4514
0.00155945
[-10.91279507]
[[ 2.21710396  3.09573722]]

After iteration: 4515
0.0015591
[-10.91326046]
[[ 2.21720576  3.09586   ]]

After iteration: 4516
0.00155875
[-10.91372585]
[[ 2.21730757  3.09598279]]

After iteration: 4517
0.0015584
[-10.91419029]
[[ 2.21740937  3.09610558]]

After iteration: 4518
0.00155806
[-10.91465473]
[[ 2.21751118  3.09622812]]

After iteration: 4519
0.00155771
[-10.91511917]
[[ 2.21761298  3.09635067]]

After iteration: 4520
0.00155736
[-10.91558361]
[[ 2.21771479  3.09647322]]

After iteration: 4521
0.00155701
[-10.91604805]
[[ 2.21781659  3.09659576]]

After iteration: 4522
0.00155666
[-10.91651249]
[[ 2.2179184   3.09671831]]

After iteration: 4523
0.00155631
[-10.91697693]
[[ 2.2180202   3.09684086]]

After iteration: 4524
0.00155596
[-10.91744137]
[[

[[ 2.23461556  3.11680269]]

After iteration: 4690
0.00150026
[-10.99308872]
[[ 2.23471379  3.11692071]]

After iteration: 4691
0.00149994
[-10.993536]
[[ 2.23481202  3.11703873]]

After iteration: 4692
0.00149961
[-10.99398327]
[[ 2.23491025  3.11715674]]

After iteration: 4693
0.00149929
[-10.99443054]
[[ 2.23500848  3.11727476]]

After iteration: 4694
0.00149897
[-10.99487782]
[[ 2.23510671  3.11739278]]

After iteration: 4695
0.00149864
[-10.99532509]
[[ 2.23520494  3.1175108 ]]

After iteration: 4696
0.00149832
[-10.99577236]
[[ 2.23530316  3.11762857]]

After iteration: 4697
0.001498
[-10.99621964]
[[ 2.23540139  3.11774635]]

After iteration: 4698
0.00149768
[-10.99666691]
[[ 2.23549938  3.11786413]]

After iteration: 4699
0.00149735
[-10.99711323]
[[ 2.23559737  3.11798191]]

After iteration: 4700
0.00149703
[-10.99755955]
[[ 2.23569536  3.11809969]]

After iteration: 4701
0.00149671
[-10.99800587]
[[ 2.23579335  3.11821747]]

After iteration: 4702
0.00149639
[-10.99845219]
[[ 

After iteration: 4836
0.00145444
[-11.05742836]
[[ 2.24884868  3.13388705]]

After iteration: 4837
0.00145413
[-11.05786228]
[[ 2.24894404  3.13400149]]

After iteration: 4838
0.00145383
[-11.0582962]
[[ 2.24903941  3.13411593]]

After iteration: 4839
0.00145353
[-11.05873013]
[[ 2.24913478  3.13423038]]

After iteration: 4840
0.00145322
[-11.05916405]
[[ 2.24923015  3.13434458]]

After iteration: 4841
0.00145292
[-11.05959797]
[[ 2.24932551  3.13445878]]

After iteration: 4842
0.00145261
[-11.06003189]
[[ 2.24942088  3.13457298]]

After iteration: 4843
0.00145231
[-11.06046486]
[[ 2.24951625  3.13468719]]

After iteration: 4844
0.00145201
[-11.06089783]
[[ 2.24961162  3.13480139]]

After iteration: 4845
0.0014517
[-11.0613308]
[[ 2.24970698  3.13491559]]

After iteration: 4846
0.0014514
[-11.06176376]
[[ 2.24980211  3.13502979]]

After iteration: 4847
0.0014511
[-11.06219673]
[[ 2.24989724  3.135144  ]]

After iteration: 4848
0.0014508
[-11.0626297]
[[ 2.24999237  3.1352582 ]]

After 

After iteration: 4962
0.00141707
[-11.11140347]
[[ 2.26072335  3.14811397]]

After iteration: 4963
0.00141678
[-11.11182594]
[[ 2.26081634  3.14822531]]

After iteration: 4964
0.00141649
[-11.11224842]
[[ 2.26090932  3.14833665]]

After iteration: 4965
0.0014162
[-11.1126709]
[[ 2.2610023   3.14844799]]

After iteration: 4966
0.00141592
[-11.11309338]
[[ 2.26109529  3.14855933]]

After iteration: 4967
0.00141563
[-11.11351585]
[[ 2.26118827  3.14867067]]

After iteration: 4968
0.00141534
[-11.11393833]
[[ 2.26128125  3.14878201]]

After iteration: 4969
0.00141505
[-11.11436081]
[[ 2.26137424  3.14889336]]

After iteration: 4970
0.00141476
[-11.11478329]
[[ 2.26146722  3.1490047 ]]

After iteration: 4971
0.00141447
[-11.11520576]
[[ 2.2615602   3.14911604]]

After iteration: 4972
0.00141418
[-11.11562824]
[[ 2.26165318  3.14922714]]

After iteration: 4973
0.0014139
[-11.11604977]
[[ 2.26174617  3.14933825]]

After iteration: 4974
0.00141361
[-11.11647129]
[[ 2.26183915  3.14944935]]

Af

[-11.16731167]
[[ 2.2730391  3.1628449]]

After iteration: 5097
0.00137909
[-11.16772366]
[[ 2.27312994  3.16295338]]

After iteration: 5098
0.00137882
[-11.16813564]
[[ 2.27322078  3.16306186]]

After iteration: 5099
0.00137854
[-11.16854668]
[[ 2.27331138  3.16317034]]

After iteration: 5100
0.00137827
[-11.16895771]
[[ 2.27340198  3.16327882]]

After iteration: 5101
0.001378
[-11.16936874]
[[ 2.27349257  3.16338706]]

After iteration: 5102
0.00137772
[-11.16977978]
[[ 2.27358317  3.1634953 ]]

After iteration: 5103
0.00137745
[-11.17019081]
[[ 2.27367377  3.16360354]]

After iteration: 5104
0.00137718
[-11.17060184]
[[ 2.27376437  3.16371179]]

After iteration: 5105
0.0013769
[-11.17101288]
[[ 2.27385497  3.16382003]]

After iteration: 5106
0.00137663
[-11.17142391]
[[ 2.27394557  3.16392827]]

After iteration: 5107
0.00137636
[-11.17183495]
[[ 2.27403617  3.16403651]]

After iteration: 5108
0.00137608
[-11.17224598]
[[ 2.27412677  3.16414475]]

After iteration: 5109
0.00137581
[-11


After iteration: 5263
0.00133507
[-11.23495388]
[[ 2.28796148  3.18065977]]

After iteration: 5264
0.00133481
[-11.23535252]
[[ 2.28804946  3.18076468]]

After iteration: 5265
0.00133456
[-11.23575115]
[[ 2.28813744  3.18086958]]

After iteration: 5266
0.0013343
[-11.23614979]
[[ 2.28822541  3.18097448]]

After iteration: 5267
0.00133404
[-11.23654842]
[[ 2.28831339  3.18107939]]

After iteration: 5268
0.00133379
[-11.23694706]
[[ 2.28840137  3.18118429]]

After iteration: 5269
0.00133353
[-11.23734474]
[[ 2.28848934  3.1812892 ]]

After iteration: 5270
0.00133327
[-11.23774242]
[[ 2.28857732  3.1813941 ]]

After iteration: 5271
0.00133302
[-11.23814011]
[[ 2.28866529  3.18149877]]

After iteration: 5272
0.00133276
[-11.23853779]
[[ 2.28875303  3.18160343]]

After iteration: 5273
0.00133251
[-11.23893547]
[[ 2.28884077  3.1817081 ]]

After iteration: 5274
0.00133225
[-11.23933315]
[[ 2.28892851  3.18181276]]

After iteration: 5275
0.001332
[-11.23973083]
[[ 2.28901625  3.18191743]]

A


After iteration: 5422
0.00129544
[-11.29737759]
[[ 2.30175376  3.19709182]]

After iteration: 5423
0.0012952
[-11.29776478]
[[ 2.30183935  3.19719362]]

After iteration: 5424
0.00129496
[-11.29815102]
[[ 2.30192494  3.19729543]]

After iteration: 5425
0.00129472
[-11.29853725]
[[ 2.30201054  3.19739723]]

After iteration: 5426
0.00129448
[-11.29892349]
[[ 2.30209589  3.19749904]]

After iteration: 5427
0.00129424
[-11.29930973]
[[ 2.30218124  3.19760084]]

After iteration: 5428
0.001294
[-11.29969597]
[[ 2.3022666   3.19770265]]

After iteration: 5429
0.00129375
[-11.30008221]
[[ 2.30235195  3.19780421]]

After iteration: 5430
0.00129351
[-11.30046844]
[[ 2.30243731  3.19790578]]

After iteration: 5431
0.00129327
[-11.30085468]
[[ 2.30252266  3.19800735]]

After iteration: 5432
0.00129303
[-11.30124092]
[[ 2.30260801  3.19810891]]

After iteration: 5433
0.00129279
[-11.30162716]
[[ 2.30269337  3.19821048]]

After iteration: 5434
0.00129255
[-11.3020134]
[[ 2.30277872  3.19831204]]

Af


After iteration: 5541
0.00126728
[-11.34290123]
[[ 2.31182551  3.20907164]]

After iteration: 5542
0.00126705
[-11.34327984]
[[ 2.3119092   3.20917106]]

After iteration: 5543
0.00126682
[-11.34365845]
[[ 2.31199288  3.20927048]]

After iteration: 5544
0.00126659
[-11.34403706]
[[ 2.31207657  3.2093699 ]]

After iteration: 5545
0.00126636
[-11.34441566]
[[ 2.31216025  3.20946932]]

After iteration: 5546
0.00126613
[-11.34479332]
[[ 2.31224394  3.20956874]]

After iteration: 5547
0.00126589
[-11.34517097]
[[ 2.31232762  3.20966816]]

After iteration: 5548
0.00126566
[-11.34554863]
[[ 2.31241131  3.20976758]]

After iteration: 5549
0.00126543
[-11.34592628]
[[ 2.31249499  3.209867  ]]

After iteration: 5550
0.0012652
[-11.34630394]
[[ 2.31257868  3.20996642]]

After iteration: 5551
0.00126497
[-11.34668159]
[[ 2.31266236  3.21006584]]

After iteration: 5552
0.00126474
[-11.34705925]
[[ 2.31274605  3.21016526]]

After iteration: 5553
0.00126451
[-11.3474369]
[[ 2.31282973  3.21026468]]




After iteration: 5682
0.00123545
[-11.39558506]
[[ 2.32349443  3.22292924]]

After iteration: 5683
0.00123523
[-11.39595413]
[[ 2.32357621  3.22302628]]

After iteration: 5684
0.00123501
[-11.3963232]
[[ 2.32365799  3.22312331]]

After iteration: 5685
0.00123479
[-11.39669228]
[[ 2.32373977  3.22322035]]

After iteration: 5686
0.00123457
[-11.39706135]
[[ 2.32382154  3.22331738]]

After iteration: 5687
0.00123435
[-11.39743042]
[[ 2.32390332  3.22341442]]

After iteration: 5688
0.00123413
[-11.39779949]
[[ 2.3239851   3.22351146]]

After iteration: 5689
0.00123391
[-11.39816761]
[[ 2.32406688  3.22360849]]

After iteration: 5690
0.00123369
[-11.39853573]
[[ 2.32414865  3.22370529]]

After iteration: 5691
0.00123347
[-11.39890385]
[[ 2.32423019  3.22380209]]

After iteration: 5692
0.00123325
[-11.39927197]
[[ 2.32431173  3.22389889]]

After iteration: 5693
0.00123303
[-11.39964008]
[[ 2.32439327  3.22399569]]

After iteration: 5694
0.00123281
[-11.4000082]
[[ 2.32447481  3.22409248]]



After iteration: 5827
0.00120432
[-11.44841003]
[[ 2.33520889  3.23681879]]

After iteration: 5828
0.00120411
[-11.44876957]
[[ 2.33528876  3.23691344]]

After iteration: 5829
0.0012039
[-11.4491291]
[[ 2.33536863  3.23700809]]

After iteration: 5830
0.00120369
[-11.44948864]
[[ 2.3354485   3.23710251]]

After iteration: 5831
0.00120349
[-11.44984818]
[[ 2.33552837  3.23719692]]

After iteration: 5832
0.00120328
[-11.45020771]
[[ 2.33560824  3.23729134]]

After iteration: 5833
0.00120307
[-11.45056725]
[[ 2.33568811  3.23738575]]

After iteration: 5834
0.00120286
[-11.45092678]
[[ 2.33576775  3.23748016]]

After iteration: 5835
0.00120265
[-11.45128632]
[[ 2.33584738  3.23757458]]

After iteration: 5836
0.00120244
[-11.45164585]
[[ 2.33592701  3.23766899]]

After iteration: 5837
0.00120223
[-11.45200539]
[[ 2.33600664  3.2377634 ]]

After iteration: 5838
0.00120202
[-11.45236492]
[[ 2.33608627  3.23785782]]

After iteration: 5839
0.00120182
[-11.4527235]
[[ 2.3361659   3.23795223]]

Af

[-11.4911375]
[[ 2.34469533  3.2480495 ]]

After iteration: 5948
0.00117952
[-11.49148941]
[[ 2.34477353  3.248142  ]]

After iteration: 5949
0.00117932
[-11.49184132]
[[ 2.34485173  3.24823451]]

After iteration: 5950
0.00117911
[-11.49219322]
[[ 2.34492993  3.24832702]]

After iteration: 5951
0.00117891
[-11.49254513]
[[ 2.34500813  3.24841952]]

After iteration: 5952
0.00117871
[-11.49289703]
[[ 2.34508634  3.24851203]]

After iteration: 5953
0.00117851
[-11.49324894]
[[ 2.34516454  3.24860454]]

After iteration: 5954
0.00117831
[-11.49360085]
[[ 2.34524274  3.24869704]]

After iteration: 5955
0.00117811
[-11.49395275]
[[ 2.34532094  3.24878955]]

After iteration: 5956
0.00117791
[-11.49430466]
[[ 2.34539914  3.24888206]]

After iteration: 5957
0.00117771
[-11.49465656]
[[ 2.34547734  3.24897456]]

After iteration: 5958
0.00117751
[-11.49500847]
[[ 2.34555554  3.24906707]]

After iteration: 5959
0.00117731
[-11.49536037]
[[ 2.34563375  3.24915957]]

After iteration: 5960
0.00117711


After iteration: 6095
0.00115071
[-11.54265213]
[[ 2.3561461   3.26158404]]

After iteration: 6096
0.00115052
[-11.54299545]
[[ 2.35622263  3.2616744 ]]

After iteration: 6097
0.00115033
[-11.54333878]
[[ 2.35629916  3.26176476]]

After iteration: 6098
0.00115014
[-11.5436821]
[[ 2.35637569  3.26185513]]

After iteration: 6099
0.00114995
[-11.54402542]
[[ 2.35645223  3.26194549]]

After iteration: 6100
0.00114976
[-11.54436874]
[[ 2.35652852  3.26203561]]

After iteration: 6101
0.00114957
[-11.54471207]
[[ 2.35660481  3.26212573]]

After iteration: 6102
0.00114938
[-11.54505539]
[[ 2.35668111  3.26221585]]

After iteration: 6103
0.00114918
[-11.54539871]
[[ 2.3567574   3.26230597]]

After iteration: 6104
0.00114899
[-11.54574203]
[[ 2.3568337  3.2623961]]

After iteration: 6105
0.0011488
[-11.54608536]
[[ 2.35690999  3.26248622]]

After iteration: 6106
0.00114861
[-11.54642868]
[[ 2.35698628  3.26257634]]

After iteration: 6107
0.00114842
[-11.546772]
[[ 2.35706258  3.26266646]]

After

After iteration: 6241
0.00112345
[-11.59224892]
[[ 2.36718464  3.27461076]]

After iteration: 6242
0.00112327
[-11.59258461]
[[ 2.3672595   3.27469897]]

After iteration: 6243
0.00112309
[-11.5929203]
[[ 2.36733413  3.27478719]]

After iteration: 6244
0.00112291
[-11.593256]
[[ 2.36740875  3.2748754 ]]

After iteration: 6245
0.00112272
[-11.59359169]
[[ 2.36748338  3.27496338]]

After iteration: 6246
0.00112254
[-11.59392738]
[[ 2.367558    3.27505136]]

After iteration: 6247
0.00112236
[-11.59426308]
[[ 2.36763263  3.27513933]]

After iteration: 6248
0.00112218
[-11.59459877]
[[ 2.36770725  3.27522731]]

After iteration: 6249
0.001122
[-11.59493446]
[[ 2.36778188  3.27531528]]

After iteration: 6250
0.00112181
[-11.59527016]
[[ 2.3678565   3.27540326]]

After iteration: 6251
0.00112163
[-11.5956049]
[[ 2.36793113  3.27549124]]

After iteration: 6252
0.00112145
[-11.59593964]
[[ 2.36800575  3.27557921]]

After iteration: 6253
0.00112127
[-11.59627438]
[[ 2.36808038  3.27566719]]

After

[-11.64003563]
[[ 2.3778317   3.28715634]]

After iteration: 6386
0.00109762
[-11.64036369]
[[ 2.37790489  3.28724241]]

After iteration: 6387
0.00109745
[-11.64069176]
[[ 2.37797809  3.28732848]]

After iteration: 6388
0.00109727
[-11.64101982]
[[ 2.37805128  3.28741455]]

After iteration: 6389
0.0010971
[-11.64134789]
[[ 2.37812448  3.28750062]]

After iteration: 6390
0.00109692
[-11.64167595]
[[ 2.37819767  3.28758669]]

After iteration: 6391
0.00109675
[-11.64200401]
[[ 2.37827086  3.28767276]]

After iteration: 6392
0.00109658
[-11.64233208]
[[ 2.37834406  3.28775883]]

After iteration: 6393
0.0010964
[-11.64266014]
[[ 2.37841702  3.2878449 ]]

After iteration: 6394
0.00109623
[-11.6429882]
[[ 2.37848997  3.28793097]]

After iteration: 6395
0.00109605
[-11.64331532]
[[ 2.37856293  3.28801703]]

After iteration: 6396
0.00109588
[-11.64364243]
[[ 2.37863588  3.2881031 ]]

After iteration: 6397
0.00109571
[-11.64396954]
[[ 2.37870884  3.28818917]]

After iteration: 6398
0.00109554
[-


After iteration: 6536
0.00107211
[-11.68899345]
[[ 2.38875294  3.30000424]]

After iteration: 6537
0.00107194
[-11.68931389]
[[ 2.38882446  3.30008841]]

After iteration: 6538
0.00107178
[-11.68963432]
[[ 2.38889599  3.30017257]]

After iteration: 6539
0.00107161
[-11.68995476]
[[ 2.38896751  3.30025673]]

After iteration: 6540
0.00107145
[-11.69027519]
[[ 2.38903904  3.30034065]]

After iteration: 6541
0.00107128
[-11.69059563]
[[ 2.38911057  3.30042458]]

After iteration: 6542
0.00107111
[-11.69091606]
[[ 2.38918209  3.3005085 ]]

After iteration: 6543
0.00107095
[-11.6912365]
[[ 2.38925362  3.30059242]]

After iteration: 6544
0.00107078
[-11.69155693]
[[ 2.38932514  3.30067635]]

After iteration: 6545
0.00107062
[-11.69187737]
[[ 2.38939667  3.30076027]]

After iteration: 6546
0.00107045
[-11.6921978]
[[ 2.38946819  3.30084419]]

After iteration: 6547
0.00107028
[-11.69251728]
[[ 2.38953972  3.30092812]]

After iteration: 6548
0.00107012
[-11.69283676]
[[ 2.38961124  3.30101204]]



[[ 2.3992269   3.31230521]]

After iteration: 6685
0.00104791
[-11.73620033]
[[ 2.399297    3.31238747]]

After iteration: 6686
0.00104775
[-11.73651314]
[[ 2.39936709  3.31246972]]

After iteration: 6687
0.00104759
[-11.73682594]
[[ 2.39943719  3.31255198]]

After iteration: 6688
0.00104743
[-11.73713875]
[[ 2.39950705  3.31263399]]

After iteration: 6689
0.00104727
[-11.73745155]
[[ 2.3995769   3.31271601]]

After iteration: 6690
0.00104711
[-11.73776436]
[[ 2.39964676  3.31279802]]

After iteration: 6691
0.00104696
[-11.73807716]
[[ 2.39971662  3.31288004]]

After iteration: 6692
0.0010468
[-11.73838997]
[[ 2.39978647  3.31296206]]

After iteration: 6693
0.00104664
[-11.73870277]
[[ 2.39985633  3.31304407]]

After iteration: 6694
0.00104648
[-11.73901558]
[[ 2.39992619  3.31312609]]

After iteration: 6695
0.00104632
[-11.73932838]
[[ 2.39999604  3.3132081 ]]

After iteration: 6696
0.00104616
[-11.73964119]
[[ 2.4000659   3.31329012]]

After iteration: 6697
0.00104601
[-11.73995399]


After iteration: 6813
0.00102797
[-11.77591419]
[[ 2.40817547  3.32280183]]

After iteration: 6814
0.00102781
[-11.77622128]
[[ 2.40824413  3.32288241]]

After iteration: 6815
0.00102766
[-11.77652836]
[[ 2.4083128  3.322963 ]]

After iteration: 6816
0.00102751
[-11.77683544]
[[ 2.40838146  3.32304358]]

After iteration: 6817
0.00102735
[-11.77714252]
[[ 2.40845013  3.32312417]]

After iteration: 6818
0.0010272
[-11.77744961]
[[ 2.40851879  3.32320476]]

After iteration: 6819
0.00102705
[-11.77775669]
[[ 2.40858746  3.32328534]]

After iteration: 6820
0.0010269
[-11.77806377]
[[ 2.40865612  3.32336593]]

After iteration: 6821
0.00102675
[-11.77837086]
[[ 2.40872478  3.32344651]]

After iteration: 6822
0.00102659
[-11.77867794]
[[ 2.40879345  3.3235271 ]]

After iteration: 6823
0.00102644
[-11.77898502]
[[ 2.40886211  3.32360768]]

After iteration: 6824
0.00102629
[-11.77929211]
[[ 2.40893078  3.32368803]]

After iteration: 6825
0.00102613
[-11.77959919]
[[ 2.40899944  3.32376838]]

Aft

0.00100349
[-11.82571507]
[[ 2.41932106  3.33585644]]

After iteration: 6978
0.00100335
[-11.82601547]
[[ 2.41938829  3.33593512]]

After iteration: 6979
0.0010032
[-11.82631588]
[[ 2.41945553  3.33601379]]

After iteration: 6980
0.00100305
[-11.82661629]
[[ 2.41952276  3.33609247]]

After iteration: 6981
0.00100291
[-11.82691574]
[[ 2.41959     3.33617115]]

After iteration: 6982
0.00100276
[-11.82721519]
[[ 2.41965723  3.33624983]]

After iteration: 6983
0.00100262
[-11.82751465]
[[ 2.41972446  3.33632851]]

After iteration: 6984
0.00100247
[-11.8278141]
[[ 2.4197917   3.33640718]]

After iteration: 6985
0.00100233
[-11.82811356]
[[ 2.41985893  3.33648562]]

After iteration: 6986
0.00100218
[-11.82841301]
[[ 2.41992593  3.33656406]]

After iteration: 6987
0.00100204
[-11.82871246]
[[ 2.41999292  3.3366425 ]]

After iteration: 6988
0.00100189
[-11.82901192]
[[ 2.42005992  3.33672094]]

After iteration: 6989
0.00100175
[-11.82931137]
[[ 2.42012691  3.33679938]]

After iteration: 6990
0

After iteration: 7146
0.000979451
[-11.87581253]
[[ 2.43054795  3.34898424]]

After iteration: 7147
0.000979312
[-11.87610531]
[[ 2.43061352  3.34906101]]

After iteration: 7148
0.000979173
[-11.87639809]
[[ 2.43067908  3.34913778]]

After iteration: 7149
0.000979033
[-11.87669086]
[[ 2.43074465  3.34921455]]

After iteration: 7150
0.000978896
[-11.87698364]
[[ 2.43081021  3.34929132]]

After iteration: 7151
0.000978757
[-11.87727642]
[[ 2.43087578  3.3493681 ]]

After iteration: 7152
0.000978618
[-11.8775692]
[[ 2.43094134  3.34944487]]

After iteration: 7153
0.00097848
[-11.87786198]
[[ 2.43100691  3.3495214 ]]

After iteration: 7154
0.000978341
[-11.87815475]
[[ 2.43107247  3.34959793]]

After iteration: 7155
0.000978203
[-11.87844753]
[[ 2.43113804  3.34967446]]

After iteration: 7156
0.000978063
[-11.87874031]
[[ 2.4312036  3.349751 ]]

After iteration: 7157
0.000977926
[-11.87903309]
[[ 2.43126917  3.34982753]]

After iteration: 7158
0.000977786
[-11.87932587]
[[ 2.43133473  3.34

[[ 2.43991542  3.35992074]]

After iteration: 7291
0.000959717
[-11.91785526]
[[ 2.43997979  3.35999584]]

After iteration: 7292
0.000959584
[-11.91814232]
[[ 2.44004416  3.36007094]]

After iteration: 7293
0.000959451
[-11.91842937]
[[ 2.44010854  3.36014605]]

After iteration: 7294
0.000959317
[-11.91871643]
[[ 2.44017291  3.36022115]]

After iteration: 7295
0.000959185
[-11.91900349]
[[ 2.44023728  3.36029625]]

After iteration: 7296
0.00095905
[-11.91929054]
[[ 2.44030166  3.36037135]]

After iteration: 7297
0.000958918
[-11.9195776]
[[ 2.44036603  3.36044645]]

After iteration: 7298
0.000958784
[-11.91986465]
[[ 2.4404304   3.36052155]]

After iteration: 7299
0.000958651
[-11.92015171]
[[ 2.44049478  3.36059666]]

After iteration: 7300
0.000958519
[-11.92043877]
[[ 2.44055915  3.36067176]]

After iteration: 7301
0.000958384
[-11.92072582]
[[ 2.44062352  3.36074686]]

After iteration: 7302
0.00095825
[-11.92101288]
[[ 2.44068789  3.36082196]]

After iteration: 7303
0.000958119
[-11

After iteration: 7405
0.000944748
[-11.95032406]
[[ 2.44727015  3.36849761]]

After iteration: 7406
0.00094462
[-11.95060635]
[[ 2.44733357  3.36857152]]

After iteration: 7407
0.000944489
[-11.95088863]
[[ 2.44739699  3.36864543]]

After iteration: 7408
0.000944361
[-11.95117092]
[[ 2.44746041  3.36871934]]

After iteration: 7409
0.000944232
[-11.95145321]
[[ 2.44752383  3.36879325]]

After iteration: 7410
0.000944102
[-11.9517355]
[[ 2.44758725  3.36886716]]

After iteration: 7411
0.000943974
[-11.95201778]
[[ 2.44765067  3.36894107]]

After iteration: 7412
0.000943844
[-11.95230007]
[[ 2.44771409  3.36901498]]

After iteration: 7413
0.000943716
[-11.95258236]
[[ 2.44777751  3.36908889]]

After iteration: 7414
0.000943587
[-11.95286465]
[[ 2.44784093  3.3691628 ]]

After iteration: 7415
0.000943457
[-11.95314693]
[[ 2.44790435  3.36923671]]

After iteration: 7416
0.000943328
[-11.95342922]
[[ 2.44796777  3.36931062]]

After iteration: 7417
0.0009432
[-11.95371151]
[[ 2.44803119  3.36

After iteration: 7556
0.00092562
[-11.99256134]
[[ 2.45676255  3.37955284]]

After iteration: 7557
0.000925497
[-11.99283791]
[[ 2.45682478  3.37962532]]

After iteration: 7558
0.000925374
[-11.99311447]
[[ 2.45688701  3.3796978 ]]

After iteration: 7559
0.000925248
[-11.99339104]
[[ 2.45694923  3.37977028]]

After iteration: 7560
0.000925124
[-11.9936676]
[[ 2.45701146  3.37984276]]

After iteration: 7561
0.000925001
[-11.99394417]
[[ 2.45707369  3.37991524]]

After iteration: 7562
0.000924878
[-11.99422073]
[[ 2.45713592  3.37998772]]

After iteration: 7563
0.000924752
[-11.9944973]
[[ 2.45719814  3.3800602 ]]

After iteration: 7564
0.00092463
[-11.99477386]
[[ 2.45726037  3.38013268]]

After iteration: 7565
0.000924506
[-11.99505043]
[[ 2.4573226   3.38020515]]

After iteration: 7566
0.000924382
[-11.995327]
[[ 2.45738482  3.38027763]]

After iteration: 7567
0.000924258
[-11.99560356]
[[ 2.45744705  3.38035011]]

After iteration: 7568
0.000924134
[-11.99588013]
[[ 2.45750928  3.3804


After iteration: 7687
0.00090964
[-12.02852154]
[[ 2.46485209  3.38896275]]

After iteration: 7688
0.000909519
[-12.02879333]
[[ 2.46491337  3.38903403]]

After iteration: 7689
0.000909398
[-12.02906513]
[[ 2.46497464  3.38910532]]

After iteration: 7690
0.000909279
[-12.02933693]
[[ 2.46503592  3.38917661]]

After iteration: 7691
0.000909159
[-12.02960873]
[[ 2.46509719  3.38924789]]

After iteration: 7692
0.000909039
[-12.02988052]
[[ 2.46515846  3.38931894]]

After iteration: 7693
0.00090892
[-12.03015232]
[[ 2.46521974  3.38938999]]

After iteration: 7694
0.000908801
[-12.03042412]
[[ 2.46528101  3.38946104]]

After iteration: 7695
0.000908681
[-12.03069592]
[[ 2.46534228  3.38953209]]

After iteration: 7696
0.000908561
[-12.03096771]
[[ 2.46540356  3.38960314]]

After iteration: 7697
0.000908441
[-12.03123951]
[[ 2.46546483  3.38967419]]

After iteration: 7698
0.000908322
[-12.03151131]
[[ 2.4655261   3.38974524]]

After iteration: 7699
0.000908202
[-12.0317831]
[[ 2.46558738  3.

After iteration: 7825
0.000893385
[-12.06574059]
[[ 2.47323322  3.39869952]]

After iteration: 7826
0.000893269
[-12.06600761]
[[ 2.47329354  3.39876938]]

After iteration: 7827
0.000893155
[-12.06627464]
[[ 2.47335362  3.39883924]]

After iteration: 7828
0.000893039
[-12.06654167]
[[ 2.47341371  3.39890909]]

After iteration: 7829
0.000892922
[-12.0668087]
[[ 2.47347379  3.39897895]]

After iteration: 7830
0.000892807
[-12.06707573]
[[ 2.47353387  3.39904881]]

After iteration: 7831
0.000892691
[-12.06734276]
[[ 2.47359395  3.39911866]]

After iteration: 7832
0.000892577
[-12.06760979]
[[ 2.47365403  3.39918852]]

After iteration: 7833
0.000892462
[-12.06787682]
[[ 2.47371411  3.39925838]]

After iteration: 7834
0.000892345
[-12.06814384]
[[ 2.47377419  3.39932823]]

After iteration: 7835
0.00089223
[-12.06841087]
[[ 2.47383428  3.39939809]]

After iteration: 7836
0.000892114
[-12.0686779]
[[ 2.47389436  3.39946795]]

After iteration: 7837
0.000891999
[-12.06894493]
[[ 2.47395444  3.3

[[ 2.48241878  3.40935874]]

After iteration: 7980
0.000875802
[-12.10676384]
[[ 2.4824779   3.40942717]]

After iteration: 7981
0.000875691
[-12.1070261]
[[ 2.48253703  3.40949559]]

After iteration: 7982
0.000875582
[-12.10728836]
[[ 2.48259616  3.40956402]]

After iteration: 7983
0.000875469
[-12.10755062]
[[ 2.48265529  3.40963244]]

After iteration: 7984
0.000875358
[-12.10781288]
[[ 2.48271441  3.40970087]]

After iteration: 7985
0.000875247
[-12.10807514]
[[ 2.48277354  3.4097693 ]]

After iteration: 7986
0.000875136
[-12.1083374]
[[ 2.48283267  3.40983772]]

After iteration: 7987
0.000875025
[-12.10859966]
[[ 2.4828918   3.40990615]]

After iteration: 7988
0.000874914
[-12.10886192]
[[ 2.48295093  3.40997458]]

After iteration: 7989
0.000874801
[-12.10912418]
[[ 2.48301005  3.410043  ]]

After iteration: 7990
0.000874692
[-12.10938549]
[[ 2.48306918  3.41011143]]

After iteration: 7991
0.000874581
[-12.1096468]
[[ 2.48312831  3.41017985]]

After iteration: 7992
0.00087447
[-12.

[-12.15597153]
[[ 2.49358106  3.42228961]]

After iteration: 8171
0.000855058
[-12.15622711]
[[ 2.49363875  3.42235661]]

After iteration: 8172
0.000854952
[-12.1564827]
[[ 2.49369645  3.42242336]]

After iteration: 8173
0.000854848
[-12.15673828]
[[ 2.49375415  3.42249012]]

After iteration: 8174
0.000854741
[-12.15699387]
[[ 2.49381185  3.42255688]]

After iteration: 8175
0.000854635
[-12.15724945]
[[ 2.49386954  3.42262363]]

After iteration: 8176
0.000854529
[-12.15750504]
[[ 2.49392724  3.42269039]]

After iteration: 8177
0.000854424
[-12.15776062]
[[ 2.49398494  3.42275715]]

After iteration: 8178
0.000854318
[-12.1580162]
[[ 2.49404263  3.42282391]]

After iteration: 8179
0.000854212
[-12.15827179]
[[ 2.49410033  3.42289066]]

After iteration: 8180
0.000854105
[-12.15852737]
[[ 2.49415803  3.42295742]]

After iteration: 8181
0.000854001
[-12.15878296]
[[ 2.49421573  3.42302418]]

After iteration: 8182
0.000853894
[-12.15903854]
[[ 2.49427342  3.42309093]]

After iteration: 8183


[[ 2.50035143  3.430125  ]]

After iteration: 8289
0.000842723
[-12.18620872]
[[ 2.50040841  3.4301908 ]]

After iteration: 8290
0.00084262
[-12.18646049]
[[ 2.50046539  3.43025661]]

After iteration: 8291
0.000842518
[-12.18671227]
[[ 2.50052238  3.43032241]]

After iteration: 8292
0.000842414
[-12.18696404]
[[ 2.50057936  3.43038821]]

After iteration: 8293
0.000842312
[-12.18721581]
[[ 2.50063634  3.43045402]]

After iteration: 8294
0.00084221
[-12.18746758]
[[ 2.50069332  3.43051982]]

After iteration: 8295
0.000842106
[-12.18771935]
[[ 2.5007503   3.43058562]]

After iteration: 8296
0.000842004
[-12.18797112]
[[ 2.50080729  3.43065143]]

After iteration: 8297
0.0008419
[-12.18822289]
[[ 2.50086427  3.43071723]]

After iteration: 8298
0.000841799
[-12.18847466]
[[ 2.50092125  3.43078303]]

After iteration: 8299
0.000841696
[-12.18872643]
[[ 2.50097823  3.43084884]]

After iteration: 8300
0.000841593
[-12.1889782]
[[ 2.50103521  3.43091464]]

After iteration: 8301
0.00084149
[-12.18

0.000829237
[-12.21948528]
[[ 2.50793052  3.4388833 ]]

After iteration: 8423
0.000829139
[-12.21973324]
[[ 2.50798655  3.43894815]]

After iteration: 8424
0.000829039
[-12.21998119]
[[ 2.50804257  3.439013  ]]

After iteration: 8425
0.000828939
[-12.22022915]
[[ 2.5080986   3.43907785]]

After iteration: 8426
0.000828839
[-12.2204771]
[[ 2.50815463  3.4391427 ]]

After iteration: 8427
0.000828738
[-12.22072506]
[[ 2.50821066  3.43920755]]

After iteration: 8428
0.00082864
[-12.22097301]
[[ 2.50826669  3.4392724 ]]

After iteration: 8429
0.000828539
[-12.22122097]
[[ 2.50832272  3.43933725]]

After iteration: 8430
0.00082844
[-12.22146893]
[[ 2.50837874  3.4394021 ]]

After iteration: 8431
0.000828342
[-12.22171688]
[[ 2.50843477  3.43946695]]

After iteration: 8432
0.000828242
[-12.22196484]
[[ 2.5084908  3.4395318]]

After iteration: 8433
0.000828142
[-12.22221279]
[[ 2.50854683  3.43959665]]

After iteration: 8434
0.000828042
[-12.22246075]
[[ 2.50860286  3.4396615 ]]

After iterati

[[ 2.51528311  3.44737315]]

After iteration: 8555
0.000816174
[-12.25223732]
[[ 2.51533842  3.44743705]]

After iteration: 8556
0.000816078
[-12.25248146]
[[ 2.51539373  3.44750094]]

After iteration: 8557
0.00081598
[-12.2527256]
[[ 2.51544905  3.44756484]]

After iteration: 8558
0.000815885
[-12.25296974]
[[ 2.51550436  3.44762874]]

After iteration: 8559
0.000815788
[-12.25321388]
[[ 2.51555967  3.44769239]]

After iteration: 8560
0.000815691
[-12.25345802]
[[ 2.51561499  3.44775605]]

After iteration: 8561
0.000815596
[-12.25370216]
[[ 2.5156703   3.44781971]]

After iteration: 8562
0.000815499
[-12.2539463]
[[ 2.51572561  3.44788337]]

After iteration: 8563
0.000815401
[-12.25419044]
[[ 2.51578093  3.44794703]]

After iteration: 8564
0.000815305
[-12.25443459]
[[ 2.51583624  3.44801068]]

After iteration: 8565
0.000815209
[-12.25467873]
[[ 2.51589155  3.44807434]]

After iteration: 8566
0.000815112
[-12.25492287]
[[ 2.51594687  3.448138  ]]

After iteration: 8567
0.000815015
[-12

0.000805297
[-12.27990627]
[[ 2.52160192  3.45466018]]

After iteration: 8670
0.000805202
[-12.28014755]
[[ 2.52165651  3.45472312]]

After iteration: 8671
0.000805109
[-12.28038883]
[[ 2.52171111  3.45478606]]

After iteration: 8672
0.000805014
[-12.28063011]
[[ 2.52176571  3.454849  ]]

After iteration: 8673
0.000804921
[-12.28087139]
[[ 2.52182031  3.45491195]]

After iteration: 8674
0.000804827
[-12.28111267]
[[ 2.5218749   3.45497489]]

After iteration: 8675
0.000804732
[-12.28135395]
[[ 2.5219295   3.45503783]]

After iteration: 8676
0.000804638
[-12.28159523]
[[ 2.5219841   3.45510077]]

After iteration: 8677
0.000804543
[-12.28183651]
[[ 2.5220387   3.45516372]]

After iteration: 8678
0.000804449
[-12.28207779]
[[ 2.5220933   3.45522666]]

After iteration: 8679
0.000804356
[-12.28231907]
[[ 2.52214789  3.4552896 ]]

After iteration: 8680
0.00080426
[-12.28255939]
[[ 2.52220249  3.45535254]]

After iteration: 8681
0.000804168
[-12.28279972]
[[ 2.52225709  3.45541549]]

After ite

[-12.30958843]
[[ 2.52832508  3.46240902]]

After iteration: 8794
0.000793696
[-12.3098259]
[[ 2.52837896  3.46247101]]

After iteration: 8795
0.000793605
[-12.31006336]
[[ 2.52843285  3.462533  ]]

After iteration: 8796
0.000793513
[-12.31030083]
[[ 2.52848673  3.46259499]]

After iteration: 8797
0.000793422
[-12.31053829]
[[ 2.52854061  3.46265697]]

After iteration: 8798
0.000793331
[-12.31077576]
[[ 2.52859449  3.46271896]]

After iteration: 8799
0.000793239
[-12.31101322]
[[ 2.52864838  3.46278095]]

After iteration: 8800
0.000793147
[-12.31125069]
[[ 2.52870226  3.46284294]]

After iteration: 8801
0.000793057
[-12.31148815]
[[ 2.52875614  3.46290493]]

After iteration: 8802
0.000792966
[-12.31172562]
[[ 2.52881002  3.46296692]]

After iteration: 8803
0.000792874
[-12.31196308]
[[ 2.52886391  3.46302891]]

After iteration: 8804
0.000792782
[-12.31220055]
[[ 2.52891779  3.4630909 ]]

After iteration: 8805
0.000792692
[-12.31243801]
[[ 2.52897167  3.46315289]]

After iteration: 8806

[[ 2.53559637  3.47077799]]

After iteration: 8930
0.000781445
[-12.34189796]
[[ 2.53564954  3.47083902]]

After iteration: 8931
0.000781356
[-12.34213161]
[[ 2.53570271  3.47090006]]

After iteration: 8932
0.000781268
[-12.34236526]
[[ 2.53575587  3.47096109]]

After iteration: 8933
0.00078118
[-12.34259892]
[[ 2.53580904  3.47102213]]

After iteration: 8934
0.000781091
[-12.34283257]
[[ 2.53586197  3.47108316]]

After iteration: 8935
0.000781002
[-12.34306622]
[[ 2.5359149  3.4711442]]

After iteration: 8936
0.000780914
[-12.34329987]
[[ 2.53596783  3.47120523]]

After iteration: 8937
0.000780826
[-12.34353352]
[[ 2.53602076  3.47126627]]

After iteration: 8938
0.000780737
[-12.34376717]
[[ 2.53607368  3.4713273 ]]

After iteration: 8939
0.000780649
[-12.34400082]
[[ 2.53612661  3.47138834]]

After iteration: 8940
0.00078056
[-12.34423447]
[[ 2.53617954  3.47144938]]

After iteration: 8941
0.000780472
[-12.34446812]
[[ 2.53623247  3.47151041]]

After iteration: 8942
0.000780384
[-12.


After iteration: 9042
0.000771634
[-12.3679409]
[[ 2.54155612  3.47763276]]

After iteration: 9043
0.000771548
[-12.36817169]
[[ 2.54160857  3.47769308]]

After iteration: 9044
0.000771462
[-12.36840248]
[[ 2.54166102  3.4777534 ]]

After iteration: 9045
0.000771377
[-12.36863327]
[[ 2.54171348  3.47781372]]

After iteration: 9046
0.00077129
[-12.36886406]
[[ 2.54176593  3.47787404]]

After iteration: 9047
0.000771203
[-12.36909485]
[[ 2.54181838  3.47793436]]

After iteration: 9048
0.000771117
[-12.36932564]
[[ 2.54187083  3.47799468]]

After iteration: 9049
0.000771031
[-12.36955643]
[[ 2.54192328  3.478055  ]]

After iteration: 9050
0.000770944
[-12.36978722]
[[ 2.54197574  3.47811532]]

After iteration: 9051
0.000770858
[-12.37001801]
[[ 2.54202819  3.47817564]]

After iteration: 9052
0.000770771
[-12.37024879]
[[ 2.54208064  3.47823596]]

After iteration: 9053
0.000770685
[-12.37047958]
[[ 2.54213309  3.47829628]]

After iteration: 9054
0.000770599
[-12.37071037]
[[ 2.54218554  3

After iteration: 9190
0.00075904
[-12.40186214]
[[ 2.54925847  3.48647976]]

After iteration: 9191
0.000758956
[-12.40208912]
[[ 2.54931021  3.48653913]]

After iteration: 9192
0.000758874
[-12.40231609]
[[ 2.54936194  3.48659849]]

After iteration: 9193
0.00075879
[-12.40254307]
[[ 2.54941344  3.48665786]]

After iteration: 9194
0.000758706
[-12.40277004]
[[ 2.54946494  3.48671722]]

After iteration: 9195
0.000758622
[-12.40299702]
[[ 2.54951644  3.48677635]]

After iteration: 9196
0.000758539
[-12.40322399]
[[ 2.54956794  3.48683548]]

After iteration: 9197
0.000758456
[-12.40345097]
[[ 2.54961944  3.48689461]]

After iteration: 9198
0.000758372
[-12.40367794]
[[ 2.54967093  3.48695374]]

After iteration: 9199
0.000758287
[-12.40390491]
[[ 2.54972243  3.48701286]]

After iteration: 9200
0.000758204
[-12.40413189]
[[ 2.54977393  3.48707199]]

After iteration: 9201
0.00075812
[-12.40435886]
[[ 2.54982543  3.48713112]]

After iteration: 9202
0.000758037
[-12.40458584]
[[ 2.54987693  3.4

After iteration: 9299
0.000750022
[-12.4264946]
[[ 2.55485296  3.49290228]]

After iteration: 9300
0.00074994
[-12.42671967]
[[ 2.55490398  3.49296093]]

After iteration: 9301
0.000749858
[-12.42694473]
[[ 2.55495501  3.49301958]]

After iteration: 9302
0.000749777
[-12.42716885]
[[ 2.55500603  3.49307823]]

After iteration: 9303
0.000749695
[-12.42739296]
[[ 2.55505705  3.49313688]]

After iteration: 9304
0.000749614
[-12.42761707]
[[ 2.55510807  3.49319553]]

After iteration: 9305
0.000749533
[-12.42784119]
[[ 2.55515909  3.49325418]]

After iteration: 9306
0.000749451
[-12.4280653]
[[ 2.55521011  3.49331284]]

After iteration: 9307
0.000749369
[-12.42828941]
[[ 2.55526114  3.49337125]]

After iteration: 9308
0.000749287
[-12.42851353]
[[ 2.55531216  3.49342966]]

After iteration: 9309
0.000749205
[-12.42873764]
[[ 2.55536318  3.49348807]]

After iteration: 9310
0.000749124
[-12.42896175]
[[ 2.5554142   3.49354649]]

After iteration: 9311
0.000749043
[-12.42918587]
[[ 2.55546522  3.4

0.000740018
[-12.45416546]
[[ 2.56114364  3.50011587]]

After iteration: 9424
0.000739938
[-12.45438671]
[[ 2.56119394  3.50017357]]

After iteration: 9425
0.000739858
[-12.45460796]
[[ 2.56124425  3.50023127]]

After iteration: 9426
0.00073978
[-12.45482922]
[[ 2.56129456  3.50028896]]

After iteration: 9427
0.0007397
[-12.45505047]
[[ 2.56134486  3.50034666]]

After iteration: 9428
0.000739621
[-12.45527172]
[[ 2.56139517  3.50040436]]

After iteration: 9429
0.00073954
[-12.45549297]
[[ 2.56144547  3.50046206]]

After iteration: 9430
0.000739461
[-12.45571423]
[[ 2.56149578  3.50051975]]

After iteration: 9431
0.000739382
[-12.45593548]
[[ 2.56154609  3.50057745]]

After iteration: 9432
0.000739303
[-12.45615673]
[[ 2.56159639  3.50063515]]

After iteration: 9433
0.000739223
[-12.45637798]
[[ 2.5616467   3.50069284]]

After iteration: 9434
0.000739144
[-12.45659924]
[[ 2.56169701  3.50075054]]

After iteration: 9435
0.000739065
[-12.45682049]
[[ 2.56174731  3.50080824]]

After iterat

[[ 2.56829953  3.50831389]]

After iteration: 9567
0.00072873
[-12.48583794]
[[ 2.56834912  3.50837088]]

After iteration: 9568
0.000728652
[-12.48605633]
[[ 2.56839871  3.50842786]]

After iteration: 9569
0.000728576
[-12.48627472]
[[ 2.56844831  3.5084846 ]]

After iteration: 9570
0.000728497
[-12.48649311]
[[ 2.5684979   3.50854158]]

After iteration: 9571
0.000728421
[-12.4867115]
[[ 2.56854749  3.50859833]]

After iteration: 9572
0.000728344
[-12.48692989]
[[ 2.56859708  3.50865507]]

After iteration: 9573
0.000728266
[-12.48714828]
[[ 2.56864667  3.50871181]]

After iteration: 9574
0.000728188
[-12.48736668]
[[ 2.56869626  3.50876856]]

After iteration: 9575
0.000728111
[-12.48758507]
[[ 2.56874585  3.5088253 ]]

After iteration: 9576
0.000728034
[-12.48780346]
[[ 2.56879544  3.50888205]]

After iteration: 9577
0.000727957
[-12.48802185]
[[ 2.56884503  3.50893879]]

After iteration: 9578
0.000727879
[-12.48824024]
[[ 2.56889462  3.50899553]]

After iteration: 9579
0.000727803
[-1


After iteration: 9730
0.000716356
[-12.52111912]
[[ 2.57638168  3.51756191]]

After iteration: 9731
0.000716281
[-12.52133369]
[[ 2.57643056  3.5176177 ]]

After iteration: 9732
0.000716205
[-12.52154827]
[[ 2.57647943  3.51767349]]

After iteration: 9733
0.000716132
[-12.52176285]
[[ 2.57652831  3.51772928]]

After iteration: 9734
0.000716057
[-12.52197742]
[[ 2.57657719  3.51778507]]

After iteration: 9735
0.000715982
[-12.522192]
[[ 2.57662606  3.51784086]]

After iteration: 9736
0.000715907
[-12.52240658]
[[ 2.57667494  3.51789665]]

After iteration: 9737
0.000715833
[-12.52262115]
[[ 2.57672381  3.51795244]]

After iteration: 9738
0.000715759
[-12.52283573]
[[ 2.57677269  3.51800823]]

After iteration: 9739
0.000715684
[-12.52305031]
[[ 2.57682157  3.51806402]]

After iteration: 9740
0.000715609
[-12.52326488]
[[ 2.57687044  3.51811981]]

After iteration: 9741
0.000715534
[-12.52347946]
[[ 2.57691932  3.5181756 ]]

After iteration: 9742
0.000715461
[-12.52369404]
[[ 2.57696819  3


After iteration: 9849
0.000707582
[-12.54650402]
[[ 2.58216572  3.52417254]]

After iteration: 9850
0.000707508
[-12.54671574]
[[ 2.58221412  3.52422786]]

After iteration: 9851
0.000707435
[-12.54692745]
[[ 2.58226252  3.52428317]]

After iteration: 9852
0.000707363
[-12.54713917]
[[ 2.58231091  3.52433825]]

After iteration: 9853
0.00070729
[-12.54735088]
[[ 2.58235931  3.52439332]]

After iteration: 9854
0.000707217
[-12.5475626]
[[ 2.58240771  3.52444839]]

After iteration: 9855
0.000707145
[-12.54777431]
[[ 2.58245611  3.52450347]]

After iteration: 9856
0.000707072
[-12.54798603]
[[ 2.58250451  3.52455854]]

After iteration: 9857
0.000706999
[-12.54819775]
[[ 2.58255267  3.52461362]]

After iteration: 9858
0.000706927
[-12.54840946]
[[ 2.58260083  3.52466869]]

After iteration: 9859
0.000706854
[-12.54862118]
[[ 2.58264899  3.52472377]]

After iteration: 9860
0.000706782
[-12.54883289]
[[ 2.58269715  3.52477884]]

After iteration: 9861
0.00070671
[-12.54904461]
[[ 2.58274531  3.

[[ 2.58831096  3.53119326]]

After iteration: 9978
0.000698308
[-12.57367516]
[[ 2.58835864  3.53124785]]

After iteration: 9979
0.000698238
[-12.57388401]
[[ 2.58840632  3.53130245]]

After iteration: 9980
0.000698166
[-12.57409286]
[[ 2.58845401  3.53135705]]

After iteration: 9981
0.000698095
[-12.57430172]
[[ 2.58850169  3.53141141]]

After iteration: 9982
0.000698026
[-12.57451057]
[[ 2.58854938  3.53146577]]

After iteration: 9983
0.000697953
[-12.57471943]
[[ 2.58859706  3.53152013]]

After iteration: 9984
0.000697884
[-12.57492828]
[[ 2.58864474  3.53157449]]

After iteration: 9985
0.000697812
[-12.57513714]
[[ 2.58869243  3.53162885]]

After iteration: 9986
0.000697742
[-12.57534599]
[[ 2.58874011  3.53168321]]

After iteration: 9987
0.00069767
[-12.57555485]
[[ 2.58878779  3.53173757]]

After iteration: 9988
0.000697601
[-12.5757637]
[[ 2.58883548  3.53179193]]

After iteration: 9989
0.000697528
[-12.57597256]
[[ 2.58888316  3.53184628]]

After iteration: 9990
0.00069746
[-12