In [77]:
import tensorflow as tf
import numpy as np

tf.reset_default_graph()

# input vector of type scalar with length 2
x = tf.placeholder(tf.float32, [None, 2], name='x')
# target labels
target = tf.placeholder(tf.float32, [None, 1], name='target') 

# bias
b = tf.get_variable("b", [1]) 

# weights
w = tf.get_variable("w", [1,2]) # weight matrix W

dot_product = tf.add(tf.matmul(x, tf.transpose(w)), b)

output = tf.sigmoid(dot_product)
#output = tf.sign(dot_product)

mse = tf.reduce_mean(tf.square(target - output))

learning_rate = 0.4

# Define a training step using Gradient Decent to minimize the mean squared error
optimizer = tf.train.AdagradOptimizer(learning_rate=learning_rate).minimize(mse)
#optimizer = tf.train.GradientDescentOptimizer(learning_rate=learning_rate).minimize(mse)

# training data
input = np.array([[1,1],[1,2],[2,1],[1,4],[2,3],[3,3],[4,2]])
labels = np.array([[0],[0],[0],[1],[1],[1],[1]])


iterations = 10000
init = tf.global_variables_initializer()

with tf.Session() as sess:
    init.run()
    
    #for j in range(iterations):
    # Loop over all steps and perform training updates on W and b
    for i in range(iterations):      
        # Instead of MiniBatches we can use the whole set here
        xs = np.array(input)   # input
        ys = np.array(labels)  # blood pressure
        _ = sess.run(optimizer, feed_dict={ x: xs, target: ys })

        res_mse, res_w, res_b = sess.run([mse, w, b], feed_dict={ x: xs, target: ys})
        print("\nAfter iteration: %d" % i)
        #print("MSE: %f \n" % res_mse)
        print(res_mse)
        print(res_b)
        print(w.eval())


After iteration: 0
0.316148
[ 1.06800032]
[[ 0.32228127 -0.4714838 ]]

After iteration: 1
0.295783
[ 1.04467428]
[[ 0.36714506 -0.31912267]]

After iteration: 2
0.287626
[ 0.9828006]
[[ 0.33703026 -0.25810757]]

After iteration: 3
0.28004
[ 0.91506964]
[[ 0.29974797 -0.21239175]]

After iteration: 4
0.272768
[ 0.84617054]
[[ 0.26395383 -0.1705519 ]]

After iteration: 5
0.265837
[ 0.77736777]
[[ 0.23188171 -0.13016103]]

After iteration: 6
0.25926
[ 0.70901418]
[[ 0.20396689 -0.0910255 ]]

After iteration: 7
0.253029
[ 0.64122409]
[[ 0.18009993 -0.05338269]]

After iteration: 8
0.247122
[ 0.57406193]
[[ 0.16001271 -0.01743787]]

After iteration: 9
0.241511
[ 0.50758094]
[[ 0.14338396  0.01670342]]

After iteration: 10
0.236166
[ 0.44182864]
[[ 0.12987524  0.04901889]]

After iteration: 11
0.231059
[ 0.37684697]
[[ 0.11915089  0.07954492]]

After iteration: 12
0.226162
[ 0.31267247]
[[ 0.11089139  0.10835635]]

After iteration: 13
0.221455
[ 0.24933609]
[[ 0.10480072  0.13555045]]

Afte

0.0476335
[-3.60930443]
[[ 0.71123087  1.17301023]]

After iteration: 150
0.0473455
[-3.62290454]
[[ 0.71395296  1.17646229]]

After iteration: 151
0.0470609
[-3.6364193]
[[ 0.71665812  1.17989337]]

After iteration: 152
0.0467797
[-3.64984989]
[[ 0.7193467   1.18330395]]

After iteration: 153
0.0465018
[-3.66319728]
[[ 0.72201884  1.18669415]]

After iteration: 154
0.0462272
[-3.67646241]
[[ 0.7246747   1.19006419]]

After iteration: 155
0.0459558
[-3.68964624]
[[ 0.72731453  1.19341433]]

After iteration: 156
0.0456875
[-3.70274997]
[[ 0.72993851  1.1967448 ]]

After iteration: 157
0.0454224
[-3.7157743]
[[ 0.73254681  1.20005596]]

After iteration: 158
0.0451602
[-3.72872043]
[[ 0.73513955  1.2033478 ]]

After iteration: 159
0.0449011
[-3.74158907]
[[ 0.73771709  1.20662069]]

After iteration: 160
0.0446449
[-3.75438142]
[[ 0.74027944  1.20987487]]

After iteration: 161
0.0443916
[-3.76709819]
[[ 0.74282688  1.21311057]]

After iteration: 162
0.0441411
[-3.7797401]
[[ 0.74535954  1.

[[ 0.98137146  1.51805353]]

After iteration: 287
0.0258474
[-4.96167517]
[[ 0.98283929  1.51994097]]

After iteration: 288
0.0257617
[-4.96893549]
[[ 0.9843021   1.52182209]]

After iteration: 289
0.0256766
[-4.97617102]
[[ 0.98576009  1.52369714]]

After iteration: 290
0.0255921
[-4.98338223]
[[ 0.98721319  1.52556598]]

After iteration: 291
0.025508
[-4.99056959]
[[ 0.98866153  1.52742887]]

After iteration: 292
0.0254246
[-4.99773312]
[[ 0.99010503  1.52928567]]

After iteration: 293
0.0253416
[-5.0048728]
[[ 0.99154383  1.53113651]]

After iteration: 294
0.0252592
[-5.01198864]
[[ 0.99297798  1.5329814 ]]

After iteration: 295
0.0251774
[-5.01908112]
[[ 0.99440742  1.53482032]]

After iteration: 296
0.025096
[-5.02615023]
[[ 0.9958322  1.5366534]]

After iteration: 297
0.0250152
[-5.03319597]
[[ 0.9972524   1.53848064]]

After iteration: 298
0.0249349
[-5.04021883]
[[ 0.99866796  1.54030204]]

After iteration: 299
0.0248551
[-5.0472188]
[[ 1.00007904  1.54211771]]

After iteration

0.0185026
[-5.68881702]
[[ 1.12964952  1.70921814]]

After iteration: 407
0.0184584
[-5.69399405]
[[ 1.13069713  1.71057165]]

After iteration: 408
0.0184144
[-5.69915819]
[[ 1.13174224  1.71192193]]

After iteration: 409
0.0183706
[-5.70430994]
[[ 1.13278484  1.713269  ]]

After iteration: 410
0.018327
[-5.70944977]
[[ 1.13382494  1.71461296]]

After iteration: 411
0.0182836
[-5.7145772]
[[ 1.13486266  1.71595383]]

After iteration: 412
0.0182404
[-5.71969223]
[[ 1.13589799  1.71729147]]

After iteration: 413
0.0181975
[-5.72479534]
[[ 1.13693082  1.71862602]]

After iteration: 414
0.0181547
[-5.72988605]
[[ 1.13796127  1.71995747]]

After iteration: 415
0.0181121
[-5.73496485]
[[ 1.13898933  1.72128594]]

After iteration: 416
0.0180697
[-5.74003172]
[[ 1.14001501  1.72261131]]

After iteration: 417
0.0180276
[-5.74508667]
[[ 1.1410383   1.72393358]]

After iteration: 418
0.0179856
[-5.7501297]
[[ 1.14205921  1.72525287]]

After iteration: 419
0.0179438
[-5.75516081]
[[ 1.14307773  1.


After iteration: 540
0.0139977
[-6.29045391]
[[ 1.25167203  1.86700046]]

After iteration: 541
0.0139723
[-6.29436493]
[[ 1.25246716  1.86802912]]

After iteration: 542
0.0139469
[-6.2982688]
[[ 1.25326097  1.86905599]]

After iteration: 543
0.0139216
[-6.30216551]
[[ 1.25405335  1.87008095]]

After iteration: 544
0.0138964
[-6.30605507]
[[ 1.25484431  1.87110412]]

After iteration: 545
0.0138713
[-6.30993748]
[[ 1.25563383  1.87212539]]

After iteration: 546
0.0138463
[-6.31381321]
[[ 1.25642192  1.87314487]]

After iteration: 547
0.0138214
[-6.31768179]
[[ 1.2572087   1.87416255]]

After iteration: 548
0.0137966
[-6.32154322]
[[ 1.25799406  1.87517846]]

After iteration: 549
0.0137719
[-6.32539797]
[[ 1.25877798  1.87619257]]

After iteration: 550
0.0137472
[-6.32924557]
[[ 1.25956059  1.8772049 ]]

After iteration: 551
0.0137226
[-6.33308649]
[[ 1.26034176  1.87821543]]

After iteration: 552
0.0136982
[-6.33692026]
[[ 1.26112163  1.87922418]]

After iteration: 553
0.0136738
[-6.340

[-6.68928957]
[[ 1.33291578  1.97207499]]

After iteration: 653
0.0116038
[-6.69253588]
[[ 1.33357835  1.9729315 ]]

After iteration: 654
0.0115862
[-6.69577694]
[[ 1.33423996  1.97378683]]

After iteration: 655
0.0115687
[-6.69901323]
[[ 1.33490062  1.97464085]]

After iteration: 656
0.0115513
[-6.70224476]
[[ 1.3355602   1.97549355]]

After iteration: 657
0.0115338
[-6.70547152]
[[ 1.33621883  1.97634506]]

After iteration: 658
0.0115165
[-6.70869303]
[[ 1.33687651  1.97719526]]

After iteration: 659
0.0114992
[-6.71190977]
[[ 1.33753324  1.97804415]]

After iteration: 660
0.0114819
[-6.71512175]
[[ 1.33818901  1.97889185]]

After iteration: 661
0.0114647
[-6.71832895]
[[ 1.33884382  1.97973824]]

After iteration: 662
0.0114476
[-6.72153139]
[[ 1.33949769  1.98058343]]

After iteration: 663
0.0114304
[-6.72472906]
[[ 1.34015059  1.98142743]]

After iteration: 664
0.0114134
[-6.72792196]
[[ 1.34080243  1.98227012]]

After iteration: 665
0.0113964
[-6.7311101]
[[ 1.34145343  1.98311162


After iteration: 799
0.00949654
[-7.12027645]
[[ 1.42108881  2.08596253]]

After iteration: 800
0.00948471
[-7.12292957]
[[ 1.42163301  2.08666468]]

After iteration: 801
0.00947292
[-7.12557936]
[[ 1.42217648  2.08736587]]

After iteration: 802
0.00946116
[-7.1282258]
[[ 1.42271936  2.0880661 ]]

After iteration: 803
0.00944943
[-7.13086891]
[[ 1.42326152  2.08876562]]

After iteration: 804
0.00943772
[-7.13350868]
[[ 1.42380309  2.08946419]]

After iteration: 805
0.00942604
[-7.13614559]
[[ 1.42434394  2.0901618 ]]

After iteration: 806
0.00941439
[-7.13877916]
[[ 1.4248842  2.0908587]]

After iteration: 807
0.00940276
[-7.1414094]
[[ 1.42542374  2.09155464]]

After iteration: 808
0.00939117
[-7.14403629]
[[ 1.42596269  2.09224987]]

After iteration: 809
0.00937961
[-7.14665985]
[[ 1.42650092  2.09294415]]

After iteration: 810
0.00936807
[-7.14928055]
[[ 1.42703855  2.0936377 ]]

After iteration: 811
0.00935656
[-7.15189791]
[[ 1.42757547  2.09433031]]

After iteration: 812
0.00934

After iteration: 918
0.00826824
[-7.41485739]
[[ 1.48161447  2.16396904]]

After iteration: 919
0.00825925
[-7.41716814]
[[ 1.48209012  2.1645813 ]]

After iteration: 920
0.00825028
[-7.41947651]
[[ 1.48256528  2.16519284]]

After iteration: 921
0.00824133
[-7.42178202]
[[ 1.48303998  2.16580391]]

After iteration: 922
0.00823239
[-7.42408514]
[[ 1.48351419  2.16641426]]

After iteration: 923
0.00822348
[-7.42638588]
[[ 1.48398781  2.1670239 ]]

After iteration: 924
0.00821459
[-7.42868423]
[[ 1.48446095  2.16763282]]

After iteration: 925
0.00820571
[-7.43097973]
[[ 1.48493361  2.16824126]]

After iteration: 926
0.00819685
[-7.43327284]
[[ 1.4854058   2.16884899]]

After iteration: 927
0.00818801
[-7.43556356]
[[ 1.48587751  2.16945601]]

After iteration: 928
0.00817919
[-7.43785191]
[[ 1.48634863  2.17006254]]

After iteration: 929
0.0081704
[-7.44013786]
[[ 1.48681927  2.17066836]]

After iteration: 930
0.00816162
[-7.44242144]
[[ 1.48728943  2.17127347]]

After iteration: 931
0.008

After iteration: 1032
0.00735447
[-7.66332436]
[[ 1.53284633  2.22984481]]

After iteration: 1033
0.00734733
[-7.66538048]
[[ 1.53327096  2.23039007]]

After iteration: 1034
0.00734022
[-7.66743469]
[[ 1.53369522  2.23093486]]

After iteration: 1035
0.00733311
[-7.66948652]
[[ 1.53411913  2.23147917]]

After iteration: 1036
0.00732602
[-7.67153645]
[[ 1.53454256  2.232023  ]]

After iteration: 1037
0.00731894
[-7.67358446]
[[ 1.53496563  2.23256636]]

After iteration: 1038
0.00731188
[-7.67563057]
[[ 1.53538835  2.233109  ]]

After iteration: 1039
0.00730483
[-7.67767477]
[[ 1.53581059  2.23365116]]

After iteration: 1040
0.0072978
[-7.67971706]
[[ 1.53623247  2.23419285]]

After iteration: 1041
0.00729078
[-7.68175745]
[[ 1.536654    2.23473406]]

After iteration: 1042
0.00728376
[-7.68379593]
[[ 1.53707516  2.23527479]]

After iteration: 1043
0.00727677
[-7.68583202]
[[ 1.53749585  2.23581505]]

After iteration: 1044
0.00726978
[-7.68786621]
[[ 1.53791618  2.23635483]]

After iterati

[-7.92794657]
[[ 1.58760619  2.30006647]]

After iteration: 1170
0.00648469
[-7.92976189]
[[ 1.58798254  2.30054832]]

After iteration: 1171
0.00647913
[-7.93157578]
[[ 1.58835864  2.30102968]]

After iteration: 1172
0.00647359
[-7.93338776]
[[ 1.58873439  2.30151081]]

After iteration: 1173
0.00646804
[-7.93519831]
[[ 1.58910978  2.30199146]]

After iteration: 1174
0.00646251
[-7.93700743]
[[ 1.58948493  2.30247164]]

After iteration: 1175
0.00645699
[-7.93881512]
[[ 1.58985972  2.30295157]]

After iteration: 1176
0.00645148
[-7.9406209]
[[ 1.59023428  2.30343103]]

After iteration: 1177
0.00644597
[-7.94242525]
[[ 1.59060848  2.30391002]]

After iteration: 1178
0.00644048
[-7.94422817]
[[ 1.59098232  2.30438852]]

After iteration: 1179
0.00643499
[-7.94602966]
[[ 1.59135592  2.30486679]]

After iteration: 1180
0.00642952
[-7.94782972]
[[ 1.59172928  2.30534458]]

After iteration: 1181
0.00642405
[-7.94962788]
[[ 1.59210229  2.3058219 ]]

After iteration: 1182
0.00641859
[-7.9514246]


After iteration: 1290
0.00587873
[-8.13703346]
[[ 1.63102758  2.35558414]]

After iteration: 1291
0.00587415
[-8.13867855]
[[ 1.63136971  2.35602093]]

After iteration: 1292
0.00586958
[-8.14032173]
[[ 1.6317116   2.35645747]]

After iteration: 1293
0.00586501
[-8.14196396]
[[ 1.63205326  2.35689354]]

After iteration: 1294
0.00586045
[-8.14360523]
[[ 1.63239467  2.35732937]]

After iteration: 1295
0.0058559
[-8.1452446]
[[ 1.63273585  2.35776496]]

After iteration: 1296
0.00585136
[-8.14688301]
[[ 1.63307667  2.35820007]]

After iteration: 1297
0.00584682
[-8.14852047]
[[ 1.63341725  2.35863495]]

After iteration: 1298
0.0058423
[-8.15015602]
[[ 1.63375759  2.35906935]]

After iteration: 1299
0.00583777
[-8.15179062]
[[ 1.6340977   2.35950351]]

After iteration: 1300
0.00583326
[-8.15342426]
[[ 1.63443756  2.35993743]]

After iteration: 1301
0.00582875
[-8.15505695]
[[ 1.63477719  2.36037087]]

After iteration: 1302
0.00582424
[-8.15668774]
[[ 1.63511658  2.36080408]]

After iteration

After iteration: 1420
0.00533733
[-8.3408289]
[[ 1.67348862  2.40971518]]

After iteration: 1421
0.00533355
[-8.3423233]
[[ 1.67380047  2.41011214]]

After iteration: 1422
0.00532977
[-8.34381676]
[[ 1.67411208  2.41050887]]

After iteration: 1423
0.005326
[-8.3453083]
[[ 1.67442346  2.41090536]]

After iteration: 1424
0.00532224
[-8.3467989]
[[ 1.67473459  2.41130137]]

After iteration: 1425
0.00531847
[-8.34828854]
[[ 1.67504549  2.41169715]]

After iteration: 1426
0.00531472
[-8.34977722]
[[ 1.67535627  2.41209269]]

After iteration: 1427
0.00531097
[-8.35126495]
[[ 1.67566681  2.41248798]]

After iteration: 1428
0.00530722
[-8.35275173]
[[ 1.67597711  2.4128828 ]]

After iteration: 1429
0.00530348
[-8.35423756]
[[ 1.67628717  2.41327739]]

After iteration: 1430
0.00529975
[-8.35572243]
[[ 1.67659712  2.41367173]]

After iteration: 1431
0.00529602
[-8.35720634]
[[ 1.67690682  2.41406584]]

After iteration: 1432
0.0052923
[-8.35868931]
[[ 1.67721629  2.41445971]]

After iteration: 14


After iteration: 1539
0.00492168
[-8.51160526]
[[ 1.70918012  2.4550848 ]]

After iteration: 1540
0.00491847
[-8.51298332]
[[ 1.7094686   2.45545101]]

After iteration: 1541
0.00491525
[-8.51436043]
[[ 1.70975685  2.45581698]]

After iteration: 1542
0.00491203
[-8.51573658]
[[ 1.71004498  2.45618272]]

After iteration: 1543
0.00490883
[-8.51711178]
[[ 1.71033287  2.45654821]]

After iteration: 1544
0.00490562
[-8.51848602]
[[ 1.71062052  2.45691347]]

After iteration: 1545
0.00490242
[-8.51986027]
[[ 1.71090806  2.45727849]]

After iteration: 1546
0.00489923
[-8.52123356]
[[ 1.71119535  2.45764327]]

After iteration: 1547
0.00489603
[-8.5226059]
[[ 1.71148252  2.45800781]]

After iteration: 1548
0.00489284
[-8.52397728]
[[ 1.71176958  2.45837212]]

After iteration: 1549
0.00488966
[-8.52534771]
[[ 1.7120564   2.45873618]]

After iteration: 1550
0.00488648
[-8.52671719]
[[ 1.7123431   2.45910001]]

After iteration: 1551
0.0048833
[-8.52808571]
[[ 1.71262956  2.4594636 ]]

After iterati

[-8.71141815]
[[ 1.75107205  2.50817204]]

After iteration: 1692
0.00447303
[-8.71267223]
[[ 1.75133538  2.50850511]]

After iteration: 1693
0.00447037
[-8.71392536]
[[ 1.7515986   2.50883794]]

After iteration: 1694
0.00446771
[-8.71517754]
[[ 1.75186169  2.50917077]]

After iteration: 1695
0.00446505
[-8.71642971]
[[ 1.75212467  2.50950336]]

After iteration: 1696
0.00446239
[-8.71768093]
[[ 1.7523874   2.50983572]]

After iteration: 1697
0.00445974
[-8.7189312]
[[ 1.75265002  2.51016784]]

After iteration: 1698
0.00445709
[-8.72018051]
[[ 1.75291252  2.51049972]]

After iteration: 1699
0.00445444
[-8.72142887]
[[ 1.7531749   2.51083159]]

After iteration: 1700
0.0044518
[-8.72267723]
[[ 1.75343704  2.51116323]]

After iteration: 1701
0.00444916
[-8.72392464]
[[ 1.75369906  2.51149464]]

After iteration: 1702
0.00444651
[-8.72517109]
[[ 1.75396097  2.5118258 ]]

After iteration: 1703
0.00444388
[-8.72641659]
[[ 1.75422263  2.51215672]]

After iteration: 1704
0.00444125
[-8.72766209]


After iteration: 1872
0.00403903
[-8.92705727]
[[ 1.79645109  2.56545806]]

After iteration: 1873
0.00403685
[-8.92818928]
[[ 1.79668987  2.56575894]]

After iteration: 1874
0.00403467
[-8.92932129]
[[ 1.79692852  2.56605959]]

After iteration: 1875
0.0040325
[-8.93045235]
[[ 1.79716706  2.56636   ]]

After iteration: 1876
0.00403033
[-8.93158245]
[[ 1.79740548  2.56666017]]

After iteration: 1877
0.00402816
[-8.93271255]
[[ 1.79764366  2.56696033]]

After iteration: 1878
0.00402599
[-8.93384171]
[[ 1.79788184  2.56726027]]

After iteration: 1879
0.00402383
[-8.9349699]
[[ 1.7981199   2.56755996]]

After iteration: 1880
0.00402167
[-8.9360981]
[[ 1.79835773  2.56785965]]

After iteration: 1881
0.00401951
[-8.93722534]
[[ 1.79859543  2.5681591 ]]

After iteration: 1882
0.00401735
[-8.93835258]
[[ 1.79883301  2.56845832]]

After iteration: 1883
0.00401519
[-8.93947887]
[[ 1.7990706   2.56875753]]

After iteration: 1884
0.00401304
[-8.94060421]
[[ 1.79930794  2.56905651]]

After iteration

After iteration: 2037
0.00370859
[-9.1061039]
[[ 1.83426809  2.61301327]]

After iteration: 2038
0.00370675
[-9.10714436]
[[ 1.83448815  2.61328936]]

After iteration: 2039
0.00370491
[-9.10818386]
[[ 1.83470809  2.61356544]]

After iteration: 2040
0.00370308
[-9.10922337]
[[ 1.83492792  2.6138413 ]]

After iteration: 2041
0.00370124
[-9.11026192]
[[ 1.83514762  2.61411715]]

After iteration: 2042
0.00369941
[-9.11129951]
[[ 1.83536732  2.61439276]]

After iteration: 2043
0.00369758
[-9.11233711]
[[ 1.83558691  2.61466837]]

After iteration: 2044
0.00369575
[-9.11337376]
[[ 1.83580637  2.61494374]]

After iteration: 2045
0.00369393
[-9.1144104]
[[ 1.83602571  2.61521888]]

After iteration: 2046
0.0036921
[-9.11544609]
[[ 1.83624494  2.61549401]]

After iteration: 2047
0.00369028
[-9.11648178]
[[ 1.83646405  2.61576891]]

After iteration: 2048
0.00368846
[-9.11751652]
[[ 1.83668303  2.61604381]]

After iteration: 2049
0.00368664
[-9.11855125]
[[ 1.8369019   2.61631846]]

After iteration

[[ 1.86801195  2.65529442]]

After iteration: 2197
0.00343562
[-9.26631069]
[[ 1.86821663  2.65555048]]

After iteration: 2198
0.00343404
[-9.26727486]
[[ 1.8684212  2.6558063]]

After iteration: 2199
0.00343246
[-9.26823807]
[[ 1.86862576  2.65606213]]

After iteration: 2200
0.00343088
[-9.26920128]
[[ 1.8688302   2.65631795]]

After iteration: 2201
0.0034293
[-9.27016354]
[[ 1.86903453  2.65657353]]

After iteration: 2202
0.00342773
[-9.27112579]
[[ 1.86923873  2.65682888]]

After iteration: 2203
0.00342616
[-9.2720871]
[[ 1.86944282  2.65708423]]

After iteration: 2204
0.00342458
[-9.2730484]
[[ 1.86964691  2.65733933]]

After iteration: 2205
0.00342301
[-9.2740097]
[[ 1.86985087  2.65759444]]

After iteration: 2206
0.00342144
[-9.27497005]
[[ 1.87005472  2.65784955]]

After iteration: 2207
0.00341987
[-9.2759304]
[[ 1.87025845  2.65810442]]

After iteration: 2208
0.00341831
[-9.2768898]
[[ 1.87046218  2.65835929]]

After iteration: 2209
0.00341674
[-9.2778492]
[[ 1.87066579  2.6586

0.00319292
[-9.41967392]
[[ 1.90081418  2.69625831]]

After iteration: 2363
0.00319155
[-9.42057037]
[[ 1.90100503  2.69649625]]

After iteration: 2364
0.00319018
[-9.42146587]
[[ 1.90119576  2.69673395]]

After iteration: 2365
0.00318882
[-9.42236137]
[[ 1.90138638  2.69697165]]

After iteration: 2366
0.00318746
[-9.42325687]
[[ 1.901577    2.69720912]]

After iteration: 2367
0.00318609
[-9.42415142]
[[ 1.90176749  2.69744658]]

After iteration: 2368
0.00318473
[-9.42504597]
[[ 1.90195787  2.69768381]]

After iteration: 2369
0.00318337
[-9.42593956]
[[ 1.90214825  2.69792104]]

After iteration: 2370
0.00318201
[-9.42683315]
[[ 1.9023385   2.69815826]]

After iteration: 2371
0.00318065
[-9.42772675]
[[ 1.90252864  2.69839525]]

After iteration: 2372
0.0031793
[-9.42861938]
[[ 1.90271878  2.69863224]]

After iteration: 2373
0.00317794
[-9.42951202]
[[ 1.9029088   2.69886899]]

After iteration: 2374
0.00317659
[-9.43040371]
[[ 1.9030987   2.69910574]]

After iteration: 2375
0.00317523
[-

After iteration: 2534
0.00297365
[-9.56846809]
[[ 1.93253815  2.73573589]]

After iteration: 2535
0.00297246
[-9.56930351]
[[ 1.93271649  2.73595738]]

After iteration: 2536
0.00297128
[-9.57013798]
[[ 1.93289471  2.73617887]]

After iteration: 2537
0.00297009
[-9.57097244]
[[ 1.93307292  2.73640013]]

After iteration: 2538
0.00296891
[-9.57180691]
[[ 1.93325102  2.73662138]]

After iteration: 2539
0.00296772
[-9.57264042]
[[ 1.93342912  2.73684263]]

After iteration: 2540
0.00296654
[-9.57347393]
[[ 1.9336071   2.73706365]]

After iteration: 2541
0.00296536
[-9.57430649]
[[ 1.93378496  2.73728466]]

After iteration: 2542
0.00296418
[-9.57513905]
[[ 1.93396282  2.73750544]]

After iteration: 2543
0.002963
[-9.5759716]
[[ 1.93414056  2.73772621]]

After iteration: 2544
0.00296182
[-9.57680321]
[[ 1.9343183   2.73794699]]

After iteration: 2545
0.00296064
[-9.57763481]
[[ 1.93449593  2.73816752]]

After iteration: 2546
0.00295946
[-9.57846642]
[[ 1.93467343  2.73838806]]

After iteration

After iteration: 2695
0.00279384
[-9.69881058]
[[ 1.96040833  2.77030182]]

After iteration: 2696
0.00279279
[-9.69959545]
[[ 1.96057642  2.77050996]]

After iteration: 2697
0.00279174
[-9.70038033]
[[ 1.96074438  2.77071786]]

After iteration: 2698
0.00279069
[-9.70116425]
[[ 1.96091235  2.77092576]]

After iteration: 2699
0.00278964
[-9.70194817]
[[ 1.96108019  2.77113366]]

After iteration: 2700
0.0027886
[-9.70273209]
[[ 1.96124804  2.77134132]]

After iteration: 2701
0.00278755
[-9.70351505]
[[ 1.96141577  2.77154899]]

After iteration: 2702
0.00278651
[-9.70429802]
[[ 1.9615835   2.77175665]]

After iteration: 2703
0.00278546
[-9.70508099]
[[ 1.9617511   2.77196431]]

After iteration: 2704
0.00278442
[-9.705863]
[[ 1.96191871  2.77217174]]

After iteration: 2705
0.00278338
[-9.70664501]
[[ 1.9620862   2.77237916]]

After iteration: 2706
0.00278234
[-9.70742702]
[[ 1.96225369  2.77258635]]

After iteration: 2707
0.0027813
[-9.70820904]
[[ 1.96242106  2.77279353]]

After iteration:

After iteration: 2859
0.00263157
[-9.82375336]
[[ 1.98719561  2.80342078]]

After iteration: 2860
0.00263064
[-9.82449245]
[[ 1.9873544   2.80361676]]

After iteration: 2861
0.00262971
[-9.82523155]
[[ 1.98751307  2.80381274]]

After iteration: 2862
0.00262878
[-9.82597065]
[[ 1.98767173  2.80400848]]

After iteration: 2863
0.00262784
[-9.82670975]
[[ 1.98783028  2.80420423]]

After iteration: 2864
0.00262691
[-9.82744789]
[[ 1.98798883  2.80439997]]

After iteration: 2865
0.00262599
[-9.82818604]
[[ 1.98814726  2.80459547]]

After iteration: 2866
0.00262506
[-9.82892418]
[[ 1.98830569  2.80479097]]

After iteration: 2867
0.00262413
[-9.82966232]
[[ 1.98846412  2.80498648]]

After iteration: 2868
0.0026232
[-9.83039951]
[[ 1.98862243  2.80518198]]

After iteration: 2869
0.00262228
[-9.8311367]
[[ 1.98878074  2.80537724]]

After iteration: 2870
0.00262135
[-9.83187389]
[[ 1.98893893  2.80557251]]

After iteration: 2871
0.00262043
[-9.83261013]
[[ 1.98909712  2.80576777]]

After iteratio

After iteration: 3013
0.00249534
[-9.93466949]
[[ 2.01103592  2.83280802]]

After iteration: 3014
0.00249451
[-9.9353714]
[[ 2.01118684  2.83299375]]

After iteration: 3015
0.00249367
[-9.93607235]
[[ 2.01133776  2.83317947]]

After iteration: 3016
0.00249283
[-9.9367733]
[[ 2.01148868  2.8333652 ]]

After iteration: 3017
0.00249199
[-9.93747425]
[[ 2.01163936  2.83355069]]

After iteration: 3018
0.00249115
[-9.9381752]
[[ 2.01179004  2.83373618]]

After iteration: 3019
0.00249032
[-9.9388752]
[[ 2.01194072  2.83392167]]

After iteration: 3020
0.00248948
[-9.9395752]
[[ 2.0120914   2.83410716]]

After iteration: 3021
0.00248865
[-9.94027519]
[[ 2.01224208  2.83429241]]

After iteration: 3022
0.00248781
[-9.94097519]
[[ 2.01239276  2.83447766]]

After iteration: 3023
0.00248698
[-9.94167423]
[[ 2.0125432   2.83466291]]

After iteration: 3024
0.00248615
[-9.94237328]
[[ 2.01269364  2.83484817]]

After iteration: 3025
0.00248531
[-9.94307232]
[[ 2.01284409  2.83503318]]

After iteration: 

[[ 2.03402042  2.8610599 ]]

After iteration: 3170
0.00237014
[-10.04201984]
[[ 2.03416419  2.86123633]]

After iteration: 3171
0.00236938
[-10.04268646]
[[ 2.03430796  2.86141276]]

After iteration: 3172
0.00236863
[-10.04335308]
[[ 2.03445172  2.86158919]]

After iteration: 3173
0.00236787
[-10.04401875]
[[ 2.03459549  2.86176562]]

After iteration: 3174
0.00236712
[-10.04468441]
[[ 2.03473902  2.86194181]]

After iteration: 3175
0.00236636
[-10.04535007]
[[ 2.03488255  2.86211801]]

After iteration: 3176
0.0023656
[-10.04601574]
[[ 2.03502607  2.8622942 ]]

After iteration: 3177
0.00236485
[-10.04668045]
[[ 2.0351696   2.86247039]]

After iteration: 3178
0.00236409
[-10.04734516]
[[ 2.03531313  2.86264634]]

After iteration: 3179
0.00236334
[-10.04800987]
[[ 2.03545642  2.86282229]]

After iteration: 3180
0.00236259
[-10.04867458]
[[ 2.03559971  2.86299825]]

After iteration: 3181
0.00236183
[-10.04933929]
[[ 2.035743   2.8631742]]

After iteration: 3182
0.00236108
[-10.05000305]
[[

After iteration: 3292
0.00228113
[-10.12180233]
[[ 2.0513885   2.88235497]]

After iteration: 3293
0.00228043
[-10.12244415]
[[ 2.05152702  2.88252473]]

After iteration: 3294
0.00227973
[-10.12308598]
[[ 2.05166554  2.88269448]]

After iteration: 3295
0.00227903
[-10.12372684]
[[ 2.05180407  2.88286424]]

After iteration: 3296
0.00227833
[-10.12436771]
[[ 2.05194259  2.88303399]]

After iteration: 3297
0.00227763
[-10.12500858]
[[ 2.05208111  2.88320351]]

After iteration: 3298
0.00227693
[-10.12564945]
[[ 2.05221963  2.88337302]]

After iteration: 3299
0.00227623
[-10.12628937]
[[ 2.05235791  2.88354254]]

After iteration: 3300
0.00227553
[-10.12692928]
[[ 2.05249619  2.88371205]]

After iteration: 3301
0.00227483
[-10.1275692]
[[ 2.05263448  2.88388133]]

After iteration: 3302
0.00227413
[-10.12820911]
[[ 2.05277276  2.88405061]]

After iteration: 3303
0.00227343
[-10.12884903]
[[ 2.05291104  2.88421988]]

After iteration: 3304
0.00227274
[-10.12948799]
[[ 2.05304933  2.88438916]]



[-10.20174885]
[[ 2.06867886  2.90350866]]

After iteration: 3420
0.00219461
[-10.20236683]
[[ 2.06881261  2.90367198]]

After iteration: 3421
0.00219396
[-10.20298386]
[[ 2.06894636  2.9038353 ]]

After iteration: 3422
0.00219331
[-10.20360088]
[[ 2.06907988  2.90399861]]

After iteration: 3423
0.00219266
[-10.20421791]
[[ 2.06921339  2.90416193]]

After iteration: 3424
0.00219201
[-10.20483494]
[[ 2.0693469   2.90432501]]

After iteration: 3425
0.00219136
[-10.20545197]
[[ 2.06948042  2.90448809]]

After iteration: 3426
0.00219071
[-10.20606804]
[[ 2.06961393  2.90465117]]

After iteration: 3427
0.00219006
[-10.20668411]
[[ 2.06974745  2.90481424]]

After iteration: 3428
0.00218942
[-10.20730019]
[[ 2.06988072  2.90497732]]

After iteration: 3429
0.00218877
[-10.20791626]
[[ 2.070014    2.90514016]]

After iteration: 3430
0.00218812
[-10.20853233]
[[ 2.07014728  2.905303  ]]

After iteration: 3431
0.00218747
[-10.20914745]
[[ 2.07028055  2.90546584]]

After iteration: 3432
0.00218683

[-10.3030262]
[[ 2.09062672  2.93029451]]

After iteration: 3588
0.00209045
[-10.30361462]
[[ 2.09075427  2.9304502 ]]

After iteration: 3589
0.00208986
[-10.30420303]
[[ 2.09088182  2.93060565]]

After iteration: 3590
0.00208927
[-10.30479145]
[[ 2.09100938  2.9307611 ]]

After iteration: 3591
0.00208868
[-10.30537891]
[[ 2.09113693  2.93091655]]

After iteration: 3592
0.00208809
[-10.30596638]
[[ 2.09126449  2.931072  ]]

After iteration: 3593
0.00208751
[-10.30655384]
[[ 2.09139204  2.93122745]]

After iteration: 3594
0.00208692
[-10.3071413]
[[ 2.09151959  2.93138266]]

After iteration: 3595
0.00208633
[-10.30772877]
[[ 2.09164691  2.93153787]]

After iteration: 3596
0.00208574
[-10.30831623]
[[ 2.09177423  2.93169308]]

After iteration: 3597
0.00208515
[-10.30890274]
[[ 2.09190154  2.93184829]]

After iteration: 3598
0.00208456
[-10.30948925]
[[ 2.09202886  2.9320035 ]]

After iteration: 3599
0.00208398
[-10.31007576]
[[ 2.09215617  2.93215871]]

After iteration: 3600
0.00208339
[

After iteration: 3754
0.00199674
[-10.39906883]
[[ 2.11148715  2.95568156]]

After iteration: 3755
0.0019962
[-10.39963055]
[[ 2.11160946  2.9558301 ]]

After iteration: 3756
0.00199567
[-10.40019226]
[[ 2.11173153  2.95597863]]

After iteration: 3757
0.00199513
[-10.40075397]
[[ 2.1118536   2.95612717]]

After iteration: 3758
0.00199459
[-10.40131569]
[[ 2.11197567  2.95627546]]

After iteration: 3759
0.00199405
[-10.4018774]
[[ 2.11209774  2.95642376]]

After iteration: 3760
0.00199351
[-10.40243912]
[[ 2.11221981  2.95657206]]

After iteration: 3761
0.00199298
[-10.40299988]
[[ 2.11234188  2.95672035]]

After iteration: 3762
0.00199244
[-10.40356064]
[[ 2.11246395  2.95686865]]

After iteration: 3763
0.0019919
[-10.4041214]
[[ 2.11258602  2.95701694]]

After iteration: 3764
0.00199136
[-10.40468216]
[[ 2.11270785  2.957165  ]]

After iteration: 3765
0.00199083
[-10.40524292]
[[ 2.11282969  2.95731306]]

After iteration: 3766
0.00199029
[-10.40580368]
[[ 2.11295152  2.95746112]]

Aft

[-10.48605251]
[[ 2.13041949  2.97866249]]

After iteration: 3913
0.00191448
[-10.48659134]
[[ 2.13053703  2.97880483]]

After iteration: 3914
0.00191398
[-10.48713017]
[[ 2.13065457  2.97894716]]

After iteration: 3915
0.00191349
[-10.48766899]
[[ 2.13077188  2.9790895 ]]

After iteration: 3916
0.00191299
[-10.48820782]
[[ 2.13088918  2.97923183]]

After iteration: 3917
0.00191249
[-10.48874664]
[[ 2.13100648  2.97937417]]

After iteration: 3918
0.001912
[-10.48928547]
[[ 2.13112378  2.97951651]]

After iteration: 3919
0.00191151
[-10.48982334]
[[ 2.13124108  2.9796586 ]]

After iteration: 3920
0.00191101
[-10.49036121]
[[ 2.13135839  2.9798007 ]]

After iteration: 3921
0.00191051
[-10.49089909]
[[ 2.13147569  2.9799428 ]]

After iteration: 3922
0.00191002
[-10.49143696]
[[ 2.13159299  2.9800849 ]]

After iteration: 3923
0.00190953
[-10.49197483]
[[ 2.13171029  2.98022699]]

After iteration: 3924
0.00190903
[-10.4925127]
[[ 2.13182735  2.98036909]]

After iteration: 3925
0.00190854
[-

[-10.57163334]
[[ 2.14908338  3.00126171]]

After iteration: 4075
0.0018373
[-10.57215118]
[[ 2.14919639  3.00139832]]

After iteration: 4076
0.00183684
[-10.57266903]
[[ 2.1493094   3.00153494]]

After iteration: 4077
0.00183639
[-10.57318592]
[[ 2.14942241  3.00167155]]

After iteration: 4078
0.00183593
[-10.57370281]
[[ 2.14953542  3.00180817]]

After iteration: 4079
0.00183547
[-10.5742197]
[[ 2.14964819  3.00194454]]

After iteration: 4080
0.00183502
[-10.5747366]
[[ 2.14976096  3.00208092]]

After iteration: 4081
0.00183456
[-10.57525349]
[[ 2.14987373  3.00221729]]

After iteration: 4082
0.0018341
[-10.57577038]
[[ 2.14998651  3.00235367]]

After iteration: 4083
0.00183365
[-10.57628727]
[[ 2.15009928  3.00249004]]

After iteration: 4084
0.00183319
[-10.57680321]
[[ 2.15021205  3.00262642]]

After iteration: 4085
0.00183274
[-10.57731915]
[[ 2.15032482  3.00276279]]

After iteration: 4086
0.00183228
[-10.57783508]
[[ 2.15043759  3.00289893]]

After iteration: 4087
0.00183183
[-1

[-10.65285587]
[[ 2.16683102  3.02269888]]

After iteration: 4235
0.0017669
[-10.65335369]
[[ 2.16693997  3.02283025]]

After iteration: 4236
0.00176648
[-10.65385151]
[[ 2.16704893  3.02296162]]

After iteration: 4237
0.00176605
[-10.65434933]
[[ 2.16715789  3.02309299]]

After iteration: 4238
0.00176563
[-10.65484715]
[[ 2.16726661  3.02322435]]

After iteration: 4239
0.00176521
[-10.65534496]
[[ 2.16737533  3.02335548]]

After iteration: 4240
0.00176479
[-10.65584183]
[[ 2.16748405  3.02348661]]

After iteration: 4241
0.00176437
[-10.65633869]
[[ 2.16759276  3.02361774]]

After iteration: 4242
0.00176394
[-10.65683556]
[[ 2.16770148  3.02374887]]

After iteration: 4243
0.00176352
[-10.65733242]
[[ 2.1678102  3.02388  ]]

After iteration: 4244
0.0017631
[-10.65782928]
[[ 2.16791892  3.02401114]]

After iteration: 4245
0.00176268
[-10.65832615]
[[ 2.16802764  3.02414227]]

After iteration: 4246
0.00176226
[-10.65882301]
[[ 2.16813636  3.02427316]]

After iteration: 4247
0.00176184
[-1

0.00170205
[-10.73104]
[[ 2.18394732  3.04332328]]

After iteration: 4395
0.00170166
[-10.7315197]
[[ 2.18405247  3.04344964]]

After iteration: 4396
0.00170127
[-10.7319994]
[[ 2.18415761  3.043576  ]]

After iteration: 4397
0.00170087
[-10.7324791]
[[ 2.18426275  3.04370236]]

After iteration: 4398
0.00170048
[-10.73295879]
[[ 2.18436766  3.04382873]]

After iteration: 4399
0.00170009
[-10.73343754]
[[ 2.18447256  3.04395509]]

After iteration: 4400
0.0016997
[-10.73391628]
[[ 2.18457747  3.04408145]]

After iteration: 4401
0.00169931
[-10.73439503]
[[ 2.18468237  3.04420781]]

After iteration: 4402
0.00169891
[-10.73487377]
[[ 2.18478727  3.04433417]]

After iteration: 4403
0.00169852
[-10.73535252]
[[ 2.18489218  3.04446054]]

After iteration: 4404
0.00169813
[-10.73583126]
[[ 2.18499708  3.04458666]]

After iteration: 4405
0.00169774
[-10.73631001]
[[ 2.18510199  3.04471278]]

After iteration: 4406
0.00169735
[-10.73678875]
[[ 2.18520689  3.04483891]]

After iteration: 4407
0.0016

After iteration: 4545
0.00164469
[-10.80223656]
[[ 2.19956136  3.06209517]]

After iteration: 4546
0.00164432
[-10.80270004]
[[ 2.19966316  3.06221724]]

After iteration: 4547
0.00164396
[-10.80316353]
[[ 2.19976497  3.06233931]]

After iteration: 4548
0.00164359
[-10.80362701]
[[ 2.19986677  3.06246138]]

After iteration: 4549
0.00164322
[-10.8040905]
[[ 2.19996834  3.06258345]]

After iteration: 4550
0.00164286
[-10.80455399]
[[ 2.2000699   3.06270552]]

After iteration: 4551
0.00164249
[-10.80501652]
[[ 2.20017147  3.06282759]]

After iteration: 4552
0.00164212
[-10.80547905]
[[ 2.20027304  3.06294966]]

After iteration: 4553
0.00164176
[-10.80594158]
[[ 2.2003746   3.06307173]]

After iteration: 4554
0.00164139
[-10.80640411]
[[ 2.20047617  3.0631938 ]]

After iteration: 4555
0.00164103
[-10.80686665]
[[ 2.20057774  3.06331563]]

After iteration: 4556
0.00164066
[-10.80732918]
[[ 2.2006793   3.06343746]]

After iteration: 4557
0.0016403
[-10.80779171]
[[ 2.20078087  3.06355929]]

A

After iteration: 4689
0.00159345
[-10.86794472]
[[ 2.21399498  3.07941222]]

After iteration: 4690
0.00159311
[-10.8683939]
[[ 2.21409369  3.07953048]]

After iteration: 4691
0.00159276
[-10.86884308]
[[ 2.21419239  3.07964873]]

After iteration: 4692
0.00159242
[-10.86929226]
[[ 2.2142911   3.07976699]]

After iteration: 4693
0.00159207
[-10.86974144]
[[ 2.2143898   3.07988524]]

After iteration: 4694
0.00159173
[-10.87019062]
[[ 2.21448851  3.0800035 ]]

After iteration: 4695
0.00159138
[-10.87063885]
[[ 2.21458721  3.08012176]]

After iteration: 4696
0.00159104
[-10.87108707]
[[ 2.21468592  3.08024001]]

After iteration: 4697
0.0015907
[-10.8715353]
[[ 2.21478462  3.08035827]]

After iteration: 4698
0.00159035
[-10.87198353]
[[ 2.21488309  3.08047652]]

After iteration: 4699
0.00159001
[-10.87243176]
[[ 2.21498156  3.08059454]]

After iteration: 4700
0.00158967
[-10.87287998]
[[ 2.21508002  3.08071256]]

After iteration: 4701
0.00158932
[-10.87332821]
[[ 2.21517849  3.08083057]]

Af

0.00153979
[-10.93904305]
[[ 2.22963762  3.09814095]]

After iteration: 4851
0.00153946
[-10.93947697]
[[ 2.22973323  3.0982554 ]]

After iteration: 4852
0.00153914
[-10.93991089]
[[ 2.22982883  3.0983696 ]]

After iteration: 4853
0.00153882
[-10.94034481]
[[ 2.22992444  3.0984838 ]]

After iteration: 4854
0.0015385
[-10.94077873]
[[ 2.23002005  3.098598  ]]

After iteration: 4855
0.00153818
[-10.94121265]
[[ 2.23011565  3.09871221]]

After iteration: 4856
0.00153785
[-10.94164658]
[[ 2.23021126  3.09882641]]

After iteration: 4857
0.00153753
[-10.9420805]
[[ 2.23030663  3.09894061]]

After iteration: 4858
0.00153721
[-10.94251442]
[[ 2.23040199  3.09905481]]

After iteration: 4859
0.00153689
[-10.94294739]
[[ 2.23049736  3.09916902]]

After iteration: 4860
0.00153657
[-10.94338036]
[[ 2.23059273  3.09928322]]

After iteration: 4861
0.00153625
[-10.94381332]
[[ 2.2306881   3.09939742]]

After iteration: 4862
0.00153593
[-10.94424629]
[[ 2.23078346  3.09951138]]

After iteration: 4863
0

After iteration: 5011
0.00148959
[-11.00780106]
[[ 2.24479055  3.11624432]]

After iteration: 5012
0.00148929
[-11.00822067]
[[ 2.2448833   3.11635494]]

After iteration: 5013
0.00148899
[-11.00864029]
[[ 2.24497604  3.11646557]]

After iteration: 5014
0.00148869
[-11.00905991]
[[ 2.24506855  3.11657619]]

After iteration: 5015
0.00148839
[-11.00947952]
[[ 2.24516106  3.11668658]]

After iteration: 5016
0.00148808
[-11.00989914]
[[ 2.24525356  3.11679697]]

After iteration: 5017
0.00148778
[-11.01031876]
[[ 2.24534607  3.11690736]]

After iteration: 5018
0.00148748
[-11.01073837]
[[ 2.24543858  3.11701775]]

After iteration: 5019
0.00148718
[-11.01115799]
[[ 2.24553108  3.11712813]]

After iteration: 5020
0.00148688
[-11.01157761]
[[ 2.24562359  3.11723852]]

After iteration: 5021
0.00148658
[-11.01199722]
[[ 2.24571609  3.11734891]]

After iteration: 5022
0.00148628
[-11.01241684]
[[ 2.2458086  3.1174593]]

After iteration: 5023
0.00148598
[-11.0128355]
[[ 2.24590111  3.11756968]]

Af

0.00144084
[-11.07680321]
[[ 2.26002312  3.13440371]]

After iteration: 5179
0.00144056
[-11.07720947]
[[ 2.260113    3.13451052]]

After iteration: 5180
0.00144028
[-11.07761574]
[[ 2.26020265  3.13461733]]

After iteration: 5181
0.00144
[-11.078022]
[[ 2.26029229  3.13472414]]

After iteration: 5182
0.00143972
[-11.07842827]
[[ 2.26038194  3.13483095]]

After iteration: 5183
0.00143943
[-11.07883453]
[[ 2.26047158  3.13493776]]

After iteration: 5184
0.00143915
[-11.0792408]
[[ 2.26056123  3.13504457]]

After iteration: 5185
0.00143887
[-11.07964706]
[[ 2.26065087  3.13515139]]

After iteration: 5186
0.00143859
[-11.08005333]
[[ 2.26074052  3.1352582 ]]

After iteration: 5187
0.00143831
[-11.08045864]
[[ 2.26083016  3.13536501]]

After iteration: 5188
0.00143803
[-11.08086395]
[[ 2.26091981  3.13547182]]

After iteration: 5189
0.00143774
[-11.08126926]
[[ 2.26100945  3.13557863]]

After iteration: 5190
0.00143746
[-11.08167458]
[[ 2.2610991   3.13568521]]

After iteration: 5191
0.001

[-11.14399147]
[[ 2.27487874  3.15207601]]

After iteration: 5347
0.00139463
[-11.14438534]
[[ 2.27496576  3.15217948]]

After iteration: 5348
0.00139437
[-11.14477921]
[[ 2.27505279  3.15228295]]

After iteration: 5349
0.0013941
[-11.14517212]
[[ 2.27513981  3.15238643]]

After iteration: 5350
0.00139384
[-11.14556503]
[[ 2.27522683  3.1524899 ]]

After iteration: 5351
0.00139358
[-11.14595795]
[[ 2.27531385  3.15259337]]

After iteration: 5352
0.00139331
[-11.14635086]
[[ 2.27540088  3.15269685]]

After iteration: 5353
0.00139305
[-11.14674377]
[[ 2.2754879   3.15280032]]

After iteration: 5354
0.00139278
[-11.14713669]
[[ 2.27557492  3.15290356]]

After iteration: 5355
0.00139252
[-11.1475296]
[[ 2.27566195  3.15300679]]

After iteration: 5356
0.00139226
[-11.14792252]
[[ 2.27574897  3.15311003]]

After iteration: 5357
0.00139199
[-11.14831543]
[[ 2.27583599  3.15321326]]

After iteration: 5358
0.00139173
[-11.14870834]
[[ 2.27592301  3.1533165 ]]

After iteration: 5359
0.00139146
[

[-11.20831966]
[[ 2.2891252   3.16898823]]

After iteration: 5513
0.00135202
[-11.20870113]
[[ 2.28920984  3.1690886 ]]

After iteration: 5514
0.00135177
[-11.2090826]
[[ 2.28929448  3.16918898]]

After iteration: 5515
0.00135152
[-11.20946407]
[[ 2.28937912  3.16928911]]

After iteration: 5516
0.00135127
[-11.20984554]
[[ 2.28946376  3.16938925]]

After iteration: 5517
0.00135102
[-11.21022701]
[[ 2.28954816  3.16948938]]

After iteration: 5518
0.00135078
[-11.21060848]
[[ 2.28963256  3.16958952]]

After iteration: 5519
0.00135053
[-11.21098995]
[[ 2.28971696  3.16968966]]

After iteration: 5520
0.00135028
[-11.21137142]
[[ 2.28980136  3.16978979]]

After iteration: 5521
0.00135003
[-11.21175289]
[[ 2.28988576  3.16988993]]

After iteration: 5522
0.00134978
[-11.21213341]
[[ 2.28997016  3.16999006]]

After iteration: 5523
0.00134954
[-11.21251392]
[[ 2.29005456  3.1700902 ]]

After iteration: 5524
0.00134929
[-11.21289444]
[[ 2.29013896  3.17019033]]

After iteration: 5525
0.00134904


[[ 2.30362415  3.18616414]]

After iteration: 5687
0.00131004
[-11.27405357]
[[ 2.30370617  3.18626118]]

After iteration: 5688
0.00130981
[-11.2744236]
[[ 2.30378819  3.18635821]]

After iteration: 5689
0.00130957
[-11.27479362]
[[ 2.3038702   3.18645525]]

After iteration: 5690
0.00130934
[-11.27516365]
[[ 2.30395222  3.18655229]]

After iteration: 5691
0.00130911
[-11.27553272]
[[ 2.30403423  3.18664932]]

After iteration: 5692
0.00130887
[-11.27590179]
[[ 2.30411625  3.18674636]]

After iteration: 5693
0.00130864
[-11.27627087]
[[ 2.30419827  3.1868434 ]]

After iteration: 5694
0.0013084
[-11.27663994]
[[ 2.30428028  3.18694043]]

After iteration: 5695
0.00130817
[-11.27700901]
[[ 2.3043623   3.18703747]]

After iteration: 5696
0.00130794
[-11.27737808]
[[ 2.30444431  3.1871345 ]]

After iteration: 5697
0.00130771
[-11.27774715]
[[ 2.30452633  3.18723154]]

After iteration: 5698
0.00130747
[-11.27811623]
[[ 2.30460835  3.18732858]]

After iteration: 5699
0.00130724
[-11.2784853]
[[

[[ 2.31714535  3.20214987]]

After iteration: 5854
0.00127211
[-11.33490849]
[[ 2.31722522  3.20224428]]

After iteration: 5855
0.00127189
[-11.33526802]
[[ 2.31730509  3.2023387 ]]

After iteration: 5856
0.00127167
[-11.3356266]
[[ 2.31738496  3.20243287]]

After iteration: 5857
0.00127145
[-11.33598518]
[[ 2.31746483  3.20252705]]

After iteration: 5858
0.00127123
[-11.33634377]
[[ 2.3175447   3.20262122]]

After iteration: 5859
0.00127101
[-11.33670235]
[[ 2.31762457  3.2027154 ]]

After iteration: 5860
0.00127079
[-11.33706093]
[[ 2.31770444  3.20280957]]

After iteration: 5861
0.00127057
[-11.33741951]
[[ 2.31778431  3.20290375]]

After iteration: 5862
0.00127035
[-11.33777809]
[[ 2.31786394  3.20299792]]

After iteration: 5863
0.00127013
[-11.33813667]
[[ 2.31794357  3.2030921 ]]

After iteration: 5864
0.00126991
[-11.33849525]
[[ 2.3180232   3.20318627]]

After iteration: 5865
0.00126969
[-11.33885384]
[[ 2.31810284  3.20328045]]

After iteration: 5866
0.00126947
[-11.33921242]


[[ 2.33037996  3.21776628]]

After iteration: 6022
0.00123609
[-11.39438438]
[[ 2.33045769  3.21785784]]

After iteration: 6023
0.00123588
[-11.39473343]
[[ 2.33053541  3.21794939]]

After iteration: 6024
0.00123567
[-11.39508247]
[[ 2.33061314  3.21804094]]

After iteration: 6025
0.00123547
[-11.39543152]
[[ 2.33069086  3.2181325 ]]

After iteration: 6026
0.00123526
[-11.39578056]
[[ 2.33076859  3.21822405]]

After iteration: 6027
0.00123505
[-11.39612961]
[[ 2.33084631  3.2183156 ]]

After iteration: 6028
0.00123484
[-11.39647865]
[[ 2.33092403  3.21840715]]

After iteration: 6029
0.00123463
[-11.3968277]
[[ 2.33100176  3.21849871]]

After iteration: 6030
0.00123443
[-11.39717674]
[[ 2.33107948  3.21859026]]

After iteration: 6031
0.00123422
[-11.39752483]
[[ 2.33115721  3.21868181]]

After iteration: 6032
0.00123401
[-11.39787292]
[[ 2.33123469  3.21877337]]

After iteration: 6033
0.0012338
[-11.39822102]
[[ 2.33131218  3.21886492]]

After iteration: 6034
0.00123359
[-11.39856911]
[

After iteration: 6182
0.00120362
[-11.44949627]
[[ 2.34273553  3.23231912]]

After iteration: 6183
0.00120342
[-11.44983578]
[[ 2.34281135  3.23240829]]

After iteration: 6184
0.00120322
[-11.45017529]
[[ 2.34288716  3.23249745]]

After iteration: 6185
0.00120303
[-11.45051479]
[[ 2.34296298  3.23258662]]

After iteration: 6186
0.00120283
[-11.4508543]
[[ 2.3430388   3.23267579]]

After iteration: 6187
0.00120263
[-11.45119381]
[[ 2.34311461  3.23276496]]

After iteration: 6188
0.00120243
[-11.45153332]
[[ 2.34319043  3.23285413]]

After iteration: 6189
0.00120223
[-11.45187283]
[[ 2.34326625  3.2329433 ]]

After iteration: 6190
0.00120204
[-11.45221233]
[[ 2.34334183  3.23303246]]

After iteration: 6191
0.00120184
[-11.45255184]
[[ 2.34341741  3.2331214 ]]

After iteration: 6192
0.00120164
[-11.45289135]
[[ 2.34349298  3.23321033]]

After iteration: 6193
0.00120145
[-11.45323086]
[[ 2.34356856  3.23329926]]

After iteration: 6194
0.00120125
[-11.45357037]
[[ 2.34364414  3.23338819]]



[[ 2.35449147  3.24614072]]

After iteration: 6340
0.00117317
[-11.50252151]
[[ 2.35456538  3.24622774]]

After iteration: 6341
0.00117298
[-11.50285244]
[[ 2.35463929  3.24631453]]

After iteration: 6342
0.00117279
[-11.50318336]
[[ 2.3547132   3.24640131]]

After iteration: 6343
0.00117261
[-11.50351429]
[[ 2.35478711  3.24648809]]

After iteration: 6344
0.00117242
[-11.50384521]
[[ 2.35486102  3.24657488]]

After iteration: 6345
0.00117223
[-11.50417614]
[[ 2.35493493  3.24666166]]

After iteration: 6346
0.00117204
[-11.50450706]
[[ 2.35500884  3.24674845]]

After iteration: 6347
0.00117186
[-11.50483799]
[[ 2.35508275  3.24683523]]

After iteration: 6348
0.00117167
[-11.50516891]
[[ 2.35515666  3.24692202]]

After iteration: 6349
0.00117148
[-11.50549984]
[[ 2.35523057  3.2470088 ]]

After iteration: 6350
0.00117129
[-11.50583076]
[[ 2.35530448  3.24709558]]

After iteration: 6351
0.00117111
[-11.50616169]
[[ 2.35537839  3.24718237]]

After iteration: 6352
0.00117092
[-11.50649261]

After iteration: 6477
0.00114798
[-11.54743004]
[[ 2.36459565  3.25800204]]

After iteration: 6478
0.0011478
[-11.54775429]
[[ 2.36466813  3.25808716]]

After iteration: 6479
0.00114762
[-11.54807854]
[[ 2.36474061  3.25817204]]

After iteration: 6480
0.00114744
[-11.54840279]
[[ 2.36481309  3.25825691]]

After iteration: 6481
0.00114726
[-11.54872704]
[[ 2.36488557  3.25834179]]

After iteration: 6482
0.00114708
[-11.54905128]
[[ 2.36495805  3.25842667]]

After iteration: 6483
0.0011469
[-11.54937553]
[[ 2.36503053  3.25851154]]

After iteration: 6484
0.00114672
[-11.54969978]
[[ 2.36510301  3.25859642]]

After iteration: 6485
0.00114654
[-11.55002403]
[[ 2.36517549  3.2586813 ]]

After iteration: 6486
0.00114636
[-11.55034828]
[[ 2.36524796  3.25876617]]

After iteration: 6487
0.00114618
[-11.55067253]
[[ 2.36532044  3.25885105]]

After iteration: 6488
0.001146
[-11.55099583]
[[ 2.36539292  3.25893593]]

After iteration: 6489
0.00114583
[-11.55131912]
[[ 2.3654654   3.25902081]]

Aft


After iteration: 6585
0.00112887
[-11.58216476]
[[ 2.37236118  3.26710558]]

After iteration: 6586
0.00112869
[-11.58248329]
[[ 2.37243247  3.26718926]]

After iteration: 6587
0.00112852
[-11.58280182]
[[ 2.37250376  3.26727295]]

After iteration: 6588
0.00112835
[-11.58312035]
[[ 2.37257504  3.2673564 ]]

After iteration: 6589
0.00112817
[-11.58343887]
[[ 2.37264633  3.26743984]]

After iteration: 6590
0.001128
[-11.5837574]
[[ 2.37271762  3.26752329]]

After iteration: 6591
0.00112783
[-11.58407593]
[[ 2.37278891  3.26760674]]

After iteration: 6592
0.00112765
[-11.58439445]
[[ 2.37286019  3.26769018]]

After iteration: 6593
0.00112748
[-11.58471298]
[[ 2.37293148  3.26777363]]

After iteration: 6594
0.0011273
[-11.58503151]
[[ 2.37300277  3.26785707]]

After iteration: 6595
0.00112713
[-11.58535004]
[[ 2.37307405  3.26794052]]

After iteration: 6596
0.00112696
[-11.58566856]
[[ 2.37314534  3.26802397]]

After iteration: 6597
0.00112678
[-11.58598709]
[[ 2.37321663  3.26810741]]

Af

0.0011092
[-11.6185236]
[[ 2.38049674  3.27663279]]

After iteration: 6701
0.00110903
[-11.61883736]
[[ 2.38056684  3.2767148 ]]

After iteration: 6702
0.00110886
[-11.61915112]
[[ 2.38063693  3.27679682]]

After iteration: 6703
0.00110869
[-11.61946487]
[[ 2.38070703  3.27687883]]

After iteration: 6704
0.00110852
[-11.61977768]
[[ 2.38077712  3.27696085]]

After iteration: 6705
0.00110836
[-11.62009048]
[[ 2.38084722  3.27704287]]

After iteration: 6706
0.00110819
[-11.62040329]
[[ 2.38091731  3.27712488]]

After iteration: 6707
0.00110802
[-11.62071609]
[[ 2.38098741  3.2772069 ]]

After iteration: 6708
0.00110785
[-11.6210289]
[[ 2.3810575   3.27728891]]

After iteration: 6709
0.00110769
[-11.62134171]
[[ 2.3811276   3.27737093]]

After iteration: 6710
0.00110752
[-11.62165451]
[[ 2.38119769  3.27745295]]

After iteration: 6711
0.00110735
[-11.62196732]
[[ 2.38126779  3.27753496]]

After iteration: 6712
0.00110718
[-11.62228012]
[[ 2.38133788  3.27761698]]

After iteration: 6713
0.

[-11.65302372]
[[ 2.38822436  3.2856698 ]]

After iteration: 6812
0.00109068
[-11.65333176]
[[ 2.3882935   3.28575063]]

After iteration: 6813
0.00109052
[-11.65363979]
[[ 2.38836265  3.28583145]]

After iteration: 6814
0.00109036
[-11.65394783]
[[ 2.38843179  3.28591204]]

After iteration: 6815
0.0010902
[-11.65425587]
[[ 2.38850093  3.28599262]]

After iteration: 6816
0.00109003
[-11.6545639]
[[ 2.38857007  3.28607321]]

After iteration: 6817
0.00108987
[-11.65487194]
[[ 2.38863897  3.28615379]]

After iteration: 6818
0.00108971
[-11.65517998]
[[ 2.38870788  3.28623438]]

After iteration: 6819
0.00108955
[-11.65548801]
[[ 2.38877678  3.28631496]]

After iteration: 6820
0.00108939
[-11.65579605]
[[ 2.38884568  3.28639555]]

After iteration: 6821
0.00108922
[-11.65610409]
[[ 2.38891459  3.28647614]]

After iteration: 6822
0.00108906
[-11.65641212]
[[ 2.38898349  3.28655672]]

After iteration: 6823
0.0010889
[-11.65672016]
[[ 2.38905239  3.28663731]]

After iteration: 6824
0.00108874
[-

[[ 2.39698696  3.29590535]]

After iteration: 6940
0.00107026
[-11.69241333]
[[ 2.39705491  3.29598451]]

After iteration: 6941
0.00107011
[-11.69271564]
[[ 2.39712262  3.29606366]]

After iteration: 6942
0.00106995
[-11.69301796]
[[ 2.39719033  3.29614282]]

After iteration: 6943
0.00106979
[-11.69332027]
[[ 2.39725804  3.29622197]]

After iteration: 6944
0.00106964
[-11.69362259]
[[ 2.39732575  3.29630113]]

After iteration: 6945
0.00106948
[-11.6939249]
[[ 2.39739347  3.29638028]]

After iteration: 6946
0.00106932
[-11.69422722]
[[ 2.39746118  3.29645944]]

After iteration: 6947
0.00106917
[-11.69452953]
[[ 2.39752889  3.29653859]]

After iteration: 6948
0.00106901
[-11.69483185]
[[ 2.3975966   3.29661775]]

After iteration: 6949
0.00106885
[-11.69513416]
[[ 2.39766431  3.2966969 ]]

After iteration: 6950
0.0010687
[-11.69543648]
[[ 2.39773202  3.29677606]]

After iteration: 6951
0.00106854
[-11.69573879]
[[ 2.39779973  3.29685521]]

After iteration: 6952
0.00106839
[-11.69604111]
[

[-11.72661495]
[[ 2.40472794  3.30493784]]

After iteration: 7055
0.00105255
[-11.7269125]
[[ 2.40479469  3.3050158 ]]

After iteration: 7056
0.0010524
[-11.72721004]
[[ 2.40486145  3.30509377]]

After iteration: 7057
0.00105225
[-11.72750759]
[[ 2.40492821  3.30517173]]

After iteration: 7058
0.00105209
[-11.72780514]
[[ 2.40499496  3.30524945]]

After iteration: 7059
0.00105194
[-11.72810268]
[[ 2.40506172  3.30532718]]

After iteration: 7060
0.00105179
[-11.72840023]
[[ 2.40512848  3.3054049 ]]

After iteration: 7061
0.00105164
[-11.72869778]
[[ 2.40519524  3.30548263]]

After iteration: 7062
0.00105149
[-11.72899532]
[[ 2.40526199  3.30556035]]

After iteration: 7063
0.00105134
[-11.72929287]
[[ 2.40532875  3.30563807]]

After iteration: 7064
0.00105119
[-11.72959042]
[[ 2.40539551  3.3057158 ]]

After iteration: 7065
0.00105104
[-11.72988796]
[[ 2.40546227  3.30579352]]

After iteration: 7066
0.00105088
[-11.73018456]
[[ 2.40552902  3.30587125]]

After iteration: 7067
0.00105074
[

[-11.76815128]
[[ 2.4140563   3.31580734]]

After iteration: 7196
0.00103161
[-11.76844311]
[[ 2.41412187  3.31588364]]

After iteration: 7197
0.00103147
[-11.76873493]
[[ 2.41418743  3.31595993]]

After iteration: 7198
0.00103132
[-11.76902676]
[[ 2.414253    3.31603622]]

After iteration: 7199
0.00103118
[-11.76931858]
[[ 2.41431856  3.31611252]]

After iteration: 7200
0.00103103
[-11.7696104]
[[ 2.41438413  3.31618881]]

After iteration: 7201
0.00103088
[-11.76990223]
[[ 2.41444969  3.31626511]]

After iteration: 7202
0.00103074
[-11.77019405]
[[ 2.41451526  3.3163414 ]]

After iteration: 7203
0.00103059
[-11.77048588]
[[ 2.41458082  3.31641769]]

After iteration: 7204
0.00103045
[-11.77077675]
[[ 2.41464639  3.31649399]]

After iteration: 7205
0.0010303
[-11.77106762]
[[ 2.41471195  3.31657028]]

After iteration: 7206
0.00103016
[-11.77135849]
[[ 2.41477752  3.31664658]]

After iteration: 7207
0.00103001
[-11.77164936]
[[ 2.41484284  3.31672287]]

After iteration: 7208
0.00102987
[

After iteration: 7335
0.00101176
[-11.80858994]
[[ 2.42314672  3.32638693]]

After iteration: 7336
0.00101162
[-11.80887604]
[[ 2.4232111   3.32646179]]

After iteration: 7337
0.00101149
[-11.80916214]
[[ 2.42327547  3.32653666]]

After iteration: 7338
0.00101134
[-11.80944824]
[[ 2.42333984  3.32661152]]

After iteration: 7339
0.0010112
[-11.80973434]
[[ 2.42340422  3.32668638]]

After iteration: 7340
0.00101106
[-11.81002045]
[[ 2.42346859  3.32676125]]

After iteration: 7341
0.00101092
[-11.81030655]
[[ 2.42353296  3.32683611]]

After iteration: 7342
0.00101078
[-11.81059265]
[[ 2.42359734  3.32691097]]

After iteration: 7343
0.00101064
[-11.81087875]
[[ 2.42366171  3.3269856 ]]

After iteration: 7344
0.0010105
[-11.81116486]
[[ 2.42372608  3.32706022]]

After iteration: 7345
0.00101036
[-11.81145096]
[[ 2.42379045  3.32713485]]

After iteration: 7346
0.00101023
[-11.81173706]
[[ 2.42385483  3.32720947]]

After iteration: 7347
0.00101009
[-11.81202221]
[[ 2.42391896  3.3272841 ]]

A

0.000996587
[-11.83982182]
[[ 2.43017364  3.33455372]]

After iteration: 7446
0.000996451
[-11.84010315]
[[ 2.43023705  3.33462739]]

After iteration: 7447
0.000996316
[-11.84038448]
[[ 2.43030047  3.33470106]]

After iteration: 7448
0.00099618
[-11.84066582]
[[ 2.43036389  3.33477473]]

After iteration: 7449
0.000996043
[-11.84094715]
[[ 2.43042731  3.3348484 ]]

After iteration: 7450
0.000995908
[-11.84122849]
[[ 2.43049073  3.33492208]]

After iteration: 7451
0.000995772
[-11.84150982]
[[ 2.43055415  3.33499575]]

After iteration: 7452
0.000995637
[-11.84179115]
[[ 2.43061757  3.33506942]]

After iteration: 7453
0.000995502
[-11.84207249]
[[ 2.43068099  3.33514309]]

After iteration: 7454
0.000995366
[-11.84235382]
[[ 2.43074441  3.33521676]]

After iteration: 7455
0.000995231
[-11.84263515]
[[ 2.43080783  3.33529043]]

After iteration: 7456
0.000995094
[-11.84291649]
[[ 2.43087125  3.3353641 ]]

After iteration: 7457
0.000994958
[-11.84319782]
[[ 2.43093467  3.33543777]]

After ite


After iteration: 7592
0.000976996
[-11.88083553]
[[ 2.43941092  3.34527636]]

After iteration: 7593
0.000976865
[-11.8811121]
[[ 2.43947315  3.3453486 ]]

After iteration: 7594
0.000976735
[-11.88138866]
[[ 2.43953538  3.34542084]]

After iteration: 7595
0.000976604
[-11.88166523]
[[ 2.43959761  3.34549308]]

After iteration: 7596
0.000976474
[-11.8819418]
[[ 2.43965983  3.34556532]]

After iteration: 7597
0.000976342
[-11.88221836]
[[ 2.43972206  3.34563756]]

After iteration: 7598
0.000976211
[-11.88249397]
[[ 2.43978429  3.3457098 ]]

After iteration: 7599
0.000976082
[-11.88276958]
[[ 2.43984652  3.34578204]]

After iteration: 7600
0.000975952
[-11.8830452]
[[ 2.43990874  3.34585428]]

After iteration: 7601
0.000975821
[-11.88332081]
[[ 2.43997097  3.34592652]]

After iteration: 7602
0.000975691
[-11.88359642]
[[ 2.4400332   3.34599876]]

After iteration: 7603
0.000975561
[-11.88387203]
[[ 2.44009542  3.346071  ]]

After iteration: 7604
0.00097543
[-11.88414764]
[[ 2.44015765  3.3

[-11.92105675]
[[ 2.44847846  3.35578895]]

After iteration: 7740
0.00095803
[-11.92132759]
[[ 2.4485395   3.35585976]]

After iteration: 7741
0.000957903
[-11.92159843]
[[ 2.44860053  3.35593057]]

After iteration: 7742
0.000957778
[-11.92186928]
[[ 2.44866157  3.35600138]]

After iteration: 7743
0.000957652
[-11.92214012]
[[ 2.4487226   3.35607219]]

After iteration: 7744
0.000957528
[-11.92241096]
[[ 2.44878364  3.356143  ]]

After iteration: 7745
0.000957401
[-11.92268181]
[[ 2.44884467  3.35621381]]

After iteration: 7746
0.000957276
[-11.92295265]
[[ 2.44890571  3.35628462]]

After iteration: 7747
0.000957151
[-11.9232235]
[[ 2.44896674  3.35635543]]

After iteration: 7748
0.000957024
[-11.92349434]
[[ 2.44902778  3.35642624]]

After iteration: 7749
0.000956899
[-11.92376518]
[[ 2.44908881  3.35649705]]

After iteration: 7750
0.000956773
[-11.92403603]
[[ 2.44914985  3.35656786]]

After iteration: 7751
0.000956649
[-11.92430687]
[[ 2.44921088  3.35663867]]

After iteration: 7752


After iteration: 7900
0.00093833
[-11.96423626]
[[ 2.45822263  3.36706924]]

After iteration: 7901
0.00093821
[-11.96450138]
[[ 2.45828247  3.36713862]]

After iteration: 7902
0.000938088
[-11.9647665]
[[ 2.45834231  3.367208  ]]

After iteration: 7903
0.000937968
[-11.96503162]
[[ 2.45840216  3.36727738]]

After iteration: 7904
0.000937847
[-11.96529675]
[[ 2.458462    3.36734676]]

After iteration: 7905
0.000937726
[-11.96556187]
[[ 2.45852184  3.36741614]]

After iteration: 7906
0.000937606
[-11.96582699]
[[ 2.45858169  3.36748552]]

After iteration: 7907
0.000937487
[-11.96609211]
[[ 2.45864153  3.3675549 ]]

After iteration: 7908
0.000937366
[-11.96635723]
[[ 2.45870137  3.36762428]]

After iteration: 7909
0.000937245
[-11.96662235]
[[ 2.45876122  3.36769342]]

After iteration: 7910
0.000937126
[-11.96688747]
[[ 2.45882106  3.36776257]]

After iteration: 7911
0.000937004
[-11.9671526]
[[ 2.4588809   3.36783171]]

After iteration: 7912
0.000936885
[-11.96741772]
[[ 2.45894074  3.36


After iteration: 8012
0.000925011
[-11.99375343]
[[ 2.46488833  3.37477851]]

After iteration: 8013
0.000924894
[-11.99401474]
[[ 2.46494746  3.37484694]]

After iteration: 8014
0.000924775
[-11.99427605]
[[ 2.46500659  3.37491536]]

After iteration: 8015
0.000924659
[-11.99453735]
[[ 2.46506572  3.37498379]]

After iteration: 8016
0.000924541
[-11.99479866]
[[ 2.46512485  3.37505221]]

After iteration: 8017
0.000924424
[-11.99505997]
[[ 2.46518397  3.3751204 ]]

After iteration: 8018
0.000924307
[-11.99532127]
[[ 2.4652431   3.37518859]]

After iteration: 8019
0.000924191
[-11.99558258]
[[ 2.46530223  3.37525678]]

After iteration: 8020
0.000924074
[-11.99584389]
[[ 2.46536136  3.37532496]]

After iteration: 8021
0.000923957
[-11.99610519]
[[ 2.46542048  3.37539315]]

After iteration: 8022
0.00092384
[-11.9963665]
[[ 2.46547961  3.37546134]]

After iteration: 8023
0.000923722
[-11.99662781]
[[ 2.46553874  3.37552953]]

After iteration: 8024
0.000923606
[-11.99688911]
[[ 2.46559787  3


After iteration: 8129
0.000911492
[-12.02414703]
[[ 2.47175884  3.38271499]]

After iteration: 8130
0.000911377
[-12.02440453]
[[ 2.47181726  3.38278222]]

After iteration: 8131
0.000911264
[-12.02466202]
[[ 2.47187543  3.38284945]]

After iteration: 8132
0.00091115
[-12.02491951]
[[ 2.4719336   3.38291669]]

After iteration: 8133
0.000911038
[-12.025177]
[[ 2.47199178  3.38298392]]

After iteration: 8134
0.000910924
[-12.02543449]
[[ 2.47204995  3.38305116]]

After iteration: 8135
0.000910812
[-12.02569199]
[[ 2.47210813  3.38311839]]

After iteration: 8136
0.000910697
[-12.02594948]
[[ 2.4721663   3.38318563]]

After iteration: 8137
0.000910583
[-12.02620697]
[[ 2.47222447  3.38325286]]

After iteration: 8138
0.000910469
[-12.02646446]
[[ 2.47228265  3.38332009]]

After iteration: 8139
0.000910356
[-12.02672195]
[[ 2.47234082  3.38338733]]

After iteration: 8140
0.000910242
[-12.02697945]
[[ 2.472399    3.38345456]]

After iteration: 8141
0.000910129
[-12.02723694]
[[ 2.47245717  3.

[-12.05155563]
[[ 2.4779582   3.38987041]]

After iteration: 8237
0.000899358
[-12.05181026]
[[ 2.47801566  3.38993692]]

After iteration: 8238
0.000899248
[-12.0520649]
[[ 2.47807312  3.39000344]]

After iteration: 8239
0.000899137
[-12.05231953]
[[ 2.47813058  3.39006996]]

After iteration: 8240
0.000899026
[-12.05257416]
[[ 2.47818804  3.39013624]]

After iteration: 8241
0.000898915
[-12.05282879]
[[ 2.4782455   3.39020252]]

After iteration: 8242
0.000898804
[-12.05308342]
[[ 2.47830296  3.3902688 ]]

After iteration: 8243
0.000898692
[-12.05333805]
[[ 2.47836041  3.39033508]]

After iteration: 8244
0.000898581
[-12.05359268]
[[ 2.47841787  3.39040136]]

After iteration: 8245
0.000898471
[-12.05384731]
[[ 2.47847533  3.39046764]]

After iteration: 8246
0.00089836
[-12.05410194]
[[ 2.47853279  3.39053392]]

After iteration: 8247
0.000898249
[-12.05435658]
[[ 2.47859025  3.3906002 ]]

After iteration: 8248
0.000898139
[-12.05461025]
[[ 2.47864771  3.39066648]]

After iteration: 8249


[[ 2.48419595  3.39706111]]

After iteration: 8346
0.000887432
[-12.07936478]
[[ 2.48425293  3.39712667]]

After iteration: 8347
0.000887323
[-12.07961559]
[[ 2.48430967  3.39719224]]

After iteration: 8348
0.000887216
[-12.07986641]
[[ 2.48436642  3.3972578 ]]

After iteration: 8349
0.000887108
[-12.08011723]
[[ 2.48442316  3.39732337]]

After iteration: 8350
0.000887
[-12.08036804]
[[ 2.4844799   3.39738894]]

After iteration: 8351
0.000886892
[-12.08061886]
[[ 2.48453665  3.3974545 ]]

After iteration: 8352
0.000886785
[-12.08086967]
[[ 2.48459339  3.39752007]]

After iteration: 8353
0.000886676
[-12.08112049]
[[ 2.48465014  3.39758563]]

After iteration: 8354
0.000886569
[-12.08137131]
[[ 2.48470688  3.3976512 ]]

After iteration: 8355
0.00088646
[-12.08162212]
[[ 2.48476362  3.39771676]]

After iteration: 8356
0.000886353
[-12.08187294]
[[ 2.48482037  3.39778209]]

After iteration: 8357
0.000886245
[-12.08212376]
[[ 2.48487711  3.39784741]]

After iteration: 8358
0.000886138
[-12.

[-12.11718845]
[[ 2.49282026  3.40699434]]

After iteration: 8499
0.00087121
[-12.11743546]
[[ 2.49287605  3.40705872]]

After iteration: 8500
0.000871106
[-12.11768246]
[[ 2.49293184  3.40712309]]

After iteration: 8501
0.000871
[-12.1179285]
[[ 2.49298763  3.40718746]]

After iteration: 8502
0.000870897
[-12.11817455]
[[ 2.49304342  3.40725183]]

After iteration: 8503
0.000870793
[-12.1184206]
[[ 2.49309921  3.40731621]]

After iteration: 8504
0.000870691
[-12.11866665]
[[ 2.493155    3.40738058]]

After iteration: 8505
0.000870587
[-12.1189127]
[[ 2.49321079  3.40744495]]

After iteration: 8506
0.000870481
[-12.11915874]
[[ 2.49326658  3.40750933]]

After iteration: 8507
0.000870378
[-12.11940479]
[[ 2.49332237  3.4075737 ]]

After iteration: 8508
0.000870275
[-12.11965084]
[[ 2.49337816  3.40763783]]

After iteration: 8509
0.000870172
[-12.11989689]
[[ 2.49343395  3.40770197]]

After iteration: 8510
0.000870068
[-12.12014294]
[[ 2.49348974  3.4077661 ]]

After iteration: 8511
0.000

[-12.14535141]
[[ 2.49920535  3.41434073]]

After iteration: 8614
0.0008594
[-12.1455946]
[[ 2.49926043  3.41440415]]

After iteration: 8615
0.0008593
[-12.14583778]
[[ 2.4993155   3.41446757]]

After iteration: 8616
0.000859198
[-12.14608097]
[[ 2.49937057  3.41453099]]

After iteration: 8617
0.000859096
[-12.14632416]
[[ 2.49942565  3.41459441]]

After iteration: 8618
0.000858995
[-12.14656734]
[[ 2.49948072  3.41465783]]

After iteration: 8619
0.000858895
[-12.14681053]
[[ 2.4995358   3.41472125]]

After iteration: 8620
0.000858793
[-12.14705372]
[[ 2.49959087  3.41478467]]

After iteration: 8621
0.000858691
[-12.14729691]
[[ 2.49964595  3.41484809]]

After iteration: 8622
0.00085859
[-12.14754009]
[[ 2.49970102  3.41491151]]

After iteration: 8623
0.000858489
[-12.14778328]
[[ 2.4997561   3.41497493]]

After iteration: 8624
0.000858387
[-12.14802647]
[[ 2.49981117  3.41503835]]

After iteration: 8625
0.000858288
[-12.14826965]
[[ 2.49986625  3.41510177]]

After iteration: 8626
0.00

[[ 2.50572634  3.42183709]]

After iteration: 8733
0.000847509
[-12.17434216]
[[ 2.5057807   3.42189956]]

After iteration: 8734
0.00084741
[-12.17458248]
[[ 2.50583506  3.42196202]]

After iteration: 8735
0.000847312
[-12.17482185]
[[ 2.50588942  3.42202449]]

After iteration: 8736
0.000847213
[-12.17506123]
[[ 2.50594378  3.42208695]]

After iteration: 8737
0.000847115
[-12.1753006]
[[ 2.50599813  3.42214942]]

After iteration: 8738
0.000847016
[-12.17553997]
[[ 2.50605249  3.42221189]]

After iteration: 8739
0.000846919
[-12.17577934]
[[ 2.50610685  3.42227435]]

After iteration: 8740
0.00084682
[-12.17601871]
[[ 2.50616121  3.42233682]]

After iteration: 8741
0.000846722
[-12.17625809]
[[ 2.50621557  3.42239928]]

After iteration: 8742
0.000846624
[-12.17649746]
[[ 2.50626993  3.42246175]]

After iteration: 8743
0.000846526
[-12.17673683]
[[ 2.50632429  3.42252421]]

After iteration: 8744
0.000846427
[-12.1769762]
[[ 2.50637865  3.42258668]]

After iteration: 8745
0.000846329
[-12.


After iteration: 8858
0.000835366
[-12.20411015]
[[ 2.51254034  3.42966056]]

After iteration: 8859
0.00083527
[-12.20434666]
[[ 2.51259398  3.42972207]]

After iteration: 8860
0.000835174
[-12.20458317]
[[ 2.51264763  3.42978358]]

After iteration: 8861
0.000835079
[-12.20481968]
[[ 2.51270127  3.42984509]]

After iteration: 8862
0.000834983
[-12.20505619]
[[ 2.51275492  3.42990661]]

After iteration: 8863
0.000834887
[-12.2052927]
[[ 2.51280856  3.42996812]]

After iteration: 8864
0.000834792
[-12.20552921]
[[ 2.51286221  3.43002963]]

After iteration: 8865
0.000834696
[-12.20576572]
[[ 2.51291585  3.43009114]]

After iteration: 8866
0.0008346
[-12.20600224]
[[ 2.51296949  3.43015265]]

After iteration: 8867
0.000834505
[-12.20623875]
[[ 2.51302314  3.43021417]]

After iteration: 8868
0.000834409
[-12.20647526]
[[ 2.51307678  3.43027568]]

After iteration: 8869
0.000834313
[-12.20671177]
[[ 2.51313043  3.43033719]]

After iteration: 8870
0.000834218
[-12.20694828]
[[ 2.51318407  3.4

[[ 2.5188911   3.43694377]]

After iteration: 8978
0.000824027
[-12.23229694]
[[ 2.51894403  3.43700457]]

After iteration: 8979
0.000823935
[-12.23253059]
[[ 2.51899695  3.43706536]]

After iteration: 8980
0.000823841
[-12.23276424]
[[ 2.51904988  3.43712616]]

After iteration: 8981
0.000823747
[-12.23299789]
[[ 2.51910281  3.43718696]]

After iteration: 8982
0.000823655
[-12.23323154]
[[ 2.51915574  3.43724775]]

After iteration: 8983
0.000823561
[-12.23346424]
[[ 2.51920867  3.43730855]]

After iteration: 8984
0.000823468
[-12.23369694]
[[ 2.5192616   3.43736935]]

After iteration: 8985
0.000823376
[-12.23392963]
[[ 2.51931453  3.43743014]]

After iteration: 8986
0.000823282
[-12.23416233]
[[ 2.51936746  3.43749094]]

After iteration: 8987
0.00082319
[-12.23439503]
[[ 2.51942039  3.43755174]]

After iteration: 8988
0.000823096
[-12.23462772]
[[ 2.51947331  3.43761253]]

After iteration: 8989
0.000823005
[-12.23486042]
[[ 2.51952624  3.43767333]]

After iteration: 8990
0.000822911
[-

[[ 2.52558064  3.44460988]]

After iteration: 9105
0.000812357
[-12.26171303]
[[ 2.52563286  3.44466972]]

After iteration: 9106
0.000812265
[-12.26194286]
[[ 2.52568507  3.44472957]]

After iteration: 9107
0.000812176
[-12.2621727]
[[ 2.52573729  3.44478941]]

After iteration: 9108
0.000812085
[-12.26240253]
[[ 2.5257895   3.44484925]]

After iteration: 9109
0.000811994
[-12.26263237]
[[ 2.52584171  3.4449091 ]]

After iteration: 9110
0.000811905
[-12.26286221]
[[ 2.52589393  3.44496894]]

After iteration: 9111
0.000811814
[-12.26309204]
[[ 2.52594614  3.44502878]]

After iteration: 9112
0.000811723
[-12.26332188]
[[ 2.52599835  3.44508862]]

After iteration: 9113
0.000811632
[-12.26355171]
[[ 2.52605057  3.44514847]]

After iteration: 9114
0.000811541
[-12.26378155]
[[ 2.52610278  3.44520831]]

After iteration: 9115
0.000811452
[-12.26401138]
[[ 2.52615499  3.44526815]]

After iteration: 9116
0.000811361
[-12.26424122]
[[ 2.52620721  3.445328  ]]

After iteration: 9117
0.00081127
[-1

[[ 2.5325923   3.45263982]]

After iteration: 9240
0.000800305
[-12.29253483]
[[ 2.5326438   3.45269895]]

After iteration: 9241
0.000800215
[-12.2927618]
[[ 2.53269529  3.45275807]]

After iteration: 9242
0.000800128
[-12.29298878]
[[ 2.53274679  3.45281696]]

After iteration: 9243
0.00080004
[-12.29321575]
[[ 2.53279829  3.45287585]]

After iteration: 9244
0.000799951
[-12.29344273]
[[ 2.53284979  3.45293474]]

After iteration: 9245
0.000799864
[-12.2936697]
[[ 2.53290129  3.45299363]]

After iteration: 9246
0.000799777
[-12.29389572]
[[ 2.53295279  3.45305252]]

After iteration: 9247
0.000799689
[-12.29412174]
[[ 2.53300428  3.45311141]]

After iteration: 9248
0.0007996
[-12.29434776]
[[ 2.53305578  3.4531703 ]]

After iteration: 9249
0.000799514
[-12.29457378]
[[ 2.53310728  3.45322919]]

After iteration: 9250
0.000799426
[-12.2947998]
[[ 2.53315878  3.45328808]]

After iteration: 9251
0.000799338
[-12.29502583]
[[ 2.53321028  3.45334697]]

After iteration: 9252
0.00079925
[-12.295

0.000790658
[-12.31753635]
[[ 2.53833604  3.45920944]]

After iteration: 9352
0.000790572
[-12.31776047]
[[ 2.53838706  3.45926785]]

After iteration: 9353
0.000790485
[-12.31798458]
[[ 2.53843808  3.45932603]]

After iteration: 9354
0.000790399
[-12.31820869]
[[ 2.5384891  3.4593842]]

After iteration: 9355
0.000790314
[-12.31843281]
[[ 2.53854012  3.45944238]]

After iteration: 9356
0.000790228
[-12.31865692]
[[ 2.53859115  3.45950055]]

After iteration: 9357
0.000790143
[-12.31888103]
[[ 2.53864217  3.45955873]]

After iteration: 9358
0.000790056
[-12.31910515]
[[ 2.53869319  3.4596169 ]]

After iteration: 9359
0.000789971
[-12.31932926]
[[ 2.53874421  3.45967507]]

After iteration: 9360
0.000789885
[-12.31955338]
[[ 2.53879523  3.45973325]]

After iteration: 9361
0.000789799
[-12.31977749]
[[ 2.53884625  3.45979142]]

After iteration: 9362
0.000789713
[-12.3200016]
[[ 2.53889728  3.4598496 ]]

After iteration: 9363
0.000789627
[-12.32022476]
[[ 2.5389483   3.45990777]]

After itera


After iteration: 9491
0.000778815
[-12.34864902]
[[ 2.54542422  3.46730757]]

After iteration: 9492
0.000778732
[-12.34886932]
[[ 2.54547453  3.46736503]]

After iteration: 9493
0.000778648
[-12.34908962]
[[ 2.54552484  3.46742249]]

After iteration: 9494
0.000778566
[-12.34930992]
[[ 2.54557514  3.46747994]]

After iteration: 9495
0.000778481
[-12.34953022]
[[ 2.54562545  3.4675374 ]]

After iteration: 9496
0.000778399
[-12.34975052]
[[ 2.54567575  3.46759486]]

After iteration: 9497
0.000778314
[-12.34997082]
[[ 2.54572606  3.46765232]]

After iteration: 9498
0.000778231
[-12.35019112]
[[ 2.54577637  3.46770978]]

After iteration: 9499
0.000778148
[-12.35041142]
[[ 2.54582667  3.46776724]]

After iteration: 9500
0.000778067
[-12.35063171]
[[ 2.54587698  3.4678247 ]]

After iteration: 9501
0.000777983
[-12.35085201]
[[ 2.54592729  3.46788216]]

After iteration: 9502
0.0007779
[-12.35107231]
[[ 2.54597759  3.46793962]]

After iteration: 9503
0.000777817
[-12.35129261]
[[ 2.5460279   3

[-12.38516045]
[[ 2.55375075  3.47681141]]

After iteration: 9659
0.00076506
[-12.38537693]
[[ 2.55380011  3.47686791]]

After iteration: 9660
0.00076498
[-12.38559341]
[[ 2.55384946  3.47692418]]

After iteration: 9661
0.000764899
[-12.3858099]
[[ 2.55389881  3.47698045]]

After iteration: 9662
0.000764819
[-12.38602638]
[[ 2.55394816  3.47703671]]

After iteration: 9663
0.000764738
[-12.38624287]
[[ 2.55399752  3.47709298]]

After iteration: 9664
0.000764659
[-12.38645935]
[[ 2.55404687  3.47714925]]

After iteration: 9665
0.000764577
[-12.38667583]
[[ 2.55409622  3.47720551]]

After iteration: 9666
0.000764498
[-12.38689232]
[[ 2.55414557  3.47726178]]

After iteration: 9667
0.000764418
[-12.3871088]
[[ 2.55419493  3.47731805]]

After iteration: 9668
0.000764336
[-12.38732529]
[[ 2.55424428  3.47737432]]

After iteration: 9669
0.000764257
[-12.38754177]
[[ 2.55429363  3.47743058]]

After iteration: 9670
0.000764176
[-12.38775826]
[[ 2.55434299  3.47748685]]

After iteration: 9671
0.

[[ 2.56023359  3.48420286]]

After iteration: 9791
0.000754587
[-12.41378403]
[[ 2.56028247  3.48425841]]

After iteration: 9792
0.000754509
[-12.41399765]
[[ 2.56033134  3.48431396]]

After iteration: 9793
0.00075443
[-12.41421127]
[[ 2.56038022  3.48436952]]

After iteration: 9794
0.000754352
[-12.4144249]
[[ 2.5604291   3.48442507]]

After iteration: 9795
0.000754273
[-12.41463852]
[[ 2.56047797  3.48448062]]

After iteration: 9796
0.000754194
[-12.41485214]
[[ 2.56052685  3.48453617]]

After iteration: 9797
0.000754118
[-12.41506577]
[[ 2.56057572  3.48459172]]

After iteration: 9798
0.000754039
[-12.41527939]
[[ 2.5606246   3.48464727]]

After iteration: 9799
0.000753962
[-12.41549301]
[[ 2.56067324  3.48470283]]

After iteration: 9800
0.000753884
[-12.41570663]
[[ 2.56072187  3.48475838]]

After iteration: 9801
0.000753805
[-12.41592026]
[[ 2.56077051  3.48481393]]

After iteration: 9802
0.000753727
[-12.41613388]
[[ 2.56081915  3.48486948]]

After iteration: 9803
0.000753649
[-1

[[ 2.56812525  3.49319196]]

After iteration: 9954
0.000742038
[-12.44834042]
[[ 2.56817317  3.49324656]]

After iteration: 9955
0.000741961
[-12.44855022]
[[ 2.56822109  3.49330115]]

After iteration: 9956
0.000741887
[-12.44876003]
[[ 2.56826901  3.49335575]]

After iteration: 9957
0.000741811
[-12.44896984]
[[ 2.56831694  3.49341035]]

After iteration: 9958
0.000741736
[-12.44917965]
[[ 2.56836486  3.49346495]]

After iteration: 9959
0.00074166
[-12.44938946]
[[ 2.56841278  3.49351954]]

After iteration: 9960
0.000741585
[-12.44959927]
[[ 2.5684607   3.49357414]]

After iteration: 9961
0.000741509
[-12.44980907]
[[ 2.56850863  3.49362874]]

After iteration: 9962
0.000741433
[-12.45001888]
[[ 2.56855655  3.49368334]]

After iteration: 9963
0.000741357
[-12.45022869]
[[ 2.56860447  3.49373794]]

After iteration: 9964
0.000741282
[-12.4504385]
[[ 2.56865239  3.49379253]]

After iteration: 9965
0.000741207
[-12.45064831]
[[ 2.56870031  3.49384713]]

After iteration: 9966
0.000741132
[-1